/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkEventRuleRequestActionType * `webhook` - Webhook * `script` - Script * `notification` - Notification
type BulkEventRuleRequestActionType string

// List of BulkEventRuleRequest_action_type
const (
	BULKEVENTRULEREQUESTACTIONTYPE_WEBHOOK      BulkEventRuleRequestActionType = "webhook"
	BULKEVENTRULEREQUESTACTIONTYPE_SCRIPT       BulkEventRuleRequestActionType = "script"
	BULKEVENTRULEREQUESTACTIONTYPE_NOTIFICATION BulkEventRuleRequestActionType = "notification"
)

// All allowed values of BulkEventRuleRequestActionType enum
var AllowedBulkEventRuleRequestActionTypeEnumValues = []BulkEventRuleRequestActionType{
	"webhook",
	"script",
	"notification",
}

func (v *BulkEventRuleRequestActionType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkEventRuleRequestActionType(value)
	for _, existing := range AllowedBulkEventRuleRequestActionTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkEventRuleRequestActionType", value)
}

// NewBulkEventRuleRequestActionTypeFromValue returns a pointer to a valid BulkEventRuleRequestActionType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkEventRuleRequestActionTypeFromValue(v string) (*BulkEventRuleRequestActionType, error) {
	ev := BulkEventRuleRequestActionType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkEventRuleRequestActionType: valid values are %v", v, AllowedBulkEventRuleRequestActionTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkEventRuleRequestActionType) IsValid() bool {
	for _, existing := range AllowedBulkEventRuleRequestActionTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkEventRuleRequest_action_type value
func (v BulkEventRuleRequestActionType) Ptr() *BulkEventRuleRequestActionType {
	return &v
}

type NullableBulkEventRuleRequestActionType struct {
	value *BulkEventRuleRequestActionType
	isSet bool
}

func (v NullableBulkEventRuleRequestActionType) Get() *BulkEventRuleRequestActionType {
	return v.value
}

func (v *NullableBulkEventRuleRequestActionType) Set(val *BulkEventRuleRequestActionType) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkEventRuleRequestActionType) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkEventRuleRequestActionType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkEventRuleRequestActionType(val *BulkEventRuleRequestActionType) *NullableBulkEventRuleRequestActionType {
	return &NullableBulkEventRuleRequestActionType{value: val, isSet: true}
}

func (v NullableBulkEventRuleRequestActionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkEventRuleRequestActionType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
