/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkPowerFeedRequestPowerPanel - struct for BulkPowerFeedRequestPowerPanel
type BulkPowerFeedRequestPowerPanel struct {
	BriefPowerPanelRequest *BriefPowerPanelRequest
	Int32                  *int32
}

// BriefPowerPanelRequestAsBulkPowerFeedRequestPowerPanel is a convenience function that returns BriefPowerPanelRequest wrapped in BulkPowerFeedRequestPowerPanel
func BriefPowerPanelRequestAsBulkPowerFeedRequestPowerPanel(v *BriefPowerPanelRequest) BulkPowerFeedRequestPowerPanel {
	return BulkPowerFeedRequestPowerPanel{
		BriefPowerPanelRequest: v,
	}
}

// int32AsBulkPowerFeedRequestPowerPanel is a convenience function that returns int32 wrapped in BulkPowerFeedRequestPowerPanel
func Int32AsBulkPowerFeedRequestPowerPanel(v *int32) BulkPowerFeedRequestPowerPanel {
	return BulkPowerFeedRequestPowerPanel{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkPowerFeedRequestPowerPanel) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefPowerPanelRequest
	err = newStrictDecoder(data).Decode(&dst.BriefPowerPanelRequest)
	if err == nil {
		jsonBriefPowerPanelRequest, _ := json.Marshal(dst.BriefPowerPanelRequest)
		if string(jsonBriefPowerPanelRequest) == "{}" { // empty struct
			dst.BriefPowerPanelRequest = nil
		} else {
			if err = validator.Validate(dst.BriefPowerPanelRequest); err != nil {
				dst.BriefPowerPanelRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefPowerPanelRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefPowerPanelRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkPowerFeedRequestPowerPanel)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkPowerFeedRequestPowerPanel): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(BulkPowerFeedRequestPowerPanel)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkPowerFeedRequestPowerPanel) MarshalJSON() ([]byte, error) {
	if src.BriefPowerPanelRequest != nil {
		return json.Marshal(&src.BriefPowerPanelRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkPowerFeedRequestPowerPanel) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefPowerPanelRequest != nil {
		return obj.BriefPowerPanelRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkPowerFeedRequestPowerPanel) GetActualInstanceValue() interface{} {
	if obj.BriefPowerPanelRequest != nil {
		return *obj.BriefPowerPanelRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkPowerFeedRequestPowerPanel struct {
	value *BulkPowerFeedRequestPowerPanel
	isSet bool
}

func (v NullableBulkPowerFeedRequestPowerPanel) Get() *BulkPowerFeedRequestPowerPanel {
	return v.value
}

func (v *NullableBulkPowerFeedRequestPowerPanel) Set(val *BulkPowerFeedRequestPowerPanel) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkPowerFeedRequestPowerPanel) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkPowerFeedRequestPowerPanel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkPowerFeedRequestPowerPanel(val *BulkPowerFeedRequestPowerPanel) *NullableBulkPowerFeedRequestPowerPanel {
	return &NullableBulkPowerFeedRequestPowerPanel{value: val, isSet: true}
}

func (v NullableBulkPowerFeedRequestPowerPanel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkPowerFeedRequestPowerPanel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
