/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkTokenRequestVersion * `1` - v1 * `2` - v2
type BulkTokenRequestVersion int32

// List of BulkTokenRequest_version
const (
	BULKTOKENREQUESTVERSION__1 BulkTokenRequestVersion = 1
	BULKTOKENREQUESTVERSION__2 BulkTokenRequestVersion = 2
)

// All allowed values of BulkTokenRequestVersion enum
var AllowedBulkTokenRequestVersionEnumValues = []BulkTokenRequestVersion{
	1,
	2,
}

func (v *BulkTokenRequestVersion) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkTokenRequestVersion(value)
	for _, existing := range AllowedBulkTokenRequestVersionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkTokenRequestVersion", value)
}

// NewBulkTokenRequestVersionFromValue returns a pointer to a valid BulkTokenRequestVersion
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkTokenRequestVersionFromValue(v int32) (*BulkTokenRequestVersion, error) {
	ev := BulkTokenRequestVersion(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkTokenRequestVersion: valid values are %v", v, AllowedBulkTokenRequestVersionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkTokenRequestVersion) IsValid() bool {
	for _, existing := range AllowedBulkTokenRequestVersionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkTokenRequest_version value
func (v BulkTokenRequestVersion) Ptr() *BulkTokenRequestVersion {
	return &v
}

type NullableBulkTokenRequestVersion struct {
	value *BulkTokenRequestVersion
	isSet bool
}

func (v NullableBulkTokenRequestVersion) Get() *BulkTokenRequestVersion {
	return v.value
}

func (v *NullableBulkTokenRequestVersion) Set(val *BulkTokenRequestVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkTokenRequestVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkTokenRequestVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkTokenRequestVersion(val *BulkTokenRequestVersion) *NullableBulkTokenRequestVersion {
	return &NullableBulkTokenRequestVersion{value: val, isSet: true}
}

func (v NullableBulkTokenRequestVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkTokenRequestVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
