/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkDataSourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkDataSourceRequest{}

// PatchedBulkDataSourceRequest Base serializer class for models inheriting from PrimaryModel.
type PatchedBulkDataSourceRequest struct {
	Id           int32                                     `json:"id"`
	Name         *string                                   `json:"name,omitempty"`
	Type         *BulkDataSourceRequestType                `json:"type,omitempty"`
	SourceUrl    *string                                   `json:"source_url,omitempty"`
	Enabled      *bool                                     `json:"enabled,omitempty"`
	Description  *string                                   `json:"description,omitempty"`
	SyncInterval NullableBulkDataSourceRequestSyncInterval `json:"sync_interval,omitempty"`
	Parameters   interface{}                               `json:"parameters,omitempty"`
	// Patterns (one per line) matching files or paths to ignore when syncing
	IgnoreRules          *string                      `json:"ignore_rules,omitempty"`
	Owner                NullableASNRangeRequestOwner `json:"owner,omitempty"`
	Comments             *string                      `json:"comments,omitempty"`
	Tags                 []NestedTagRequest           `json:"tags,omitempty"`
	CustomFields         map[string]interface{}       `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkDataSourceRequest PatchedBulkDataSourceRequest

// NewPatchedBulkDataSourceRequest instantiates a new PatchedBulkDataSourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkDataSourceRequest(id int32) *PatchedBulkDataSourceRequest {
	this := PatchedBulkDataSourceRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkDataSourceRequestWithDefaults instantiates a new PatchedBulkDataSourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkDataSourceRequestWithDefaults() *PatchedBulkDataSourceRequest {
	this := PatchedBulkDataSourceRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkDataSourceRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkDataSourceRequest) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedBulkDataSourceRequest) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetType() BulkDataSourceRequestType {
	if o == nil || IsNil(o.Type) {
		var ret BulkDataSourceRequestType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetTypeOk() (*BulkDataSourceRequestType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given BulkDataSourceRequestType and assigns it to the Type field.
func (o *PatchedBulkDataSourceRequest) SetType(v BulkDataSourceRequestType) {
	o.Type = &v
}

// GetSourceUrl returns the SourceUrl field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetSourceUrl() string {
	if o == nil || IsNil(o.SourceUrl) {
		var ret string
		return ret
	}
	return *o.SourceUrl
}

// GetSourceUrlOk returns a tuple with the SourceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetSourceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SourceUrl) {
		return nil, false
	}
	return o.SourceUrl, true
}

// HasSourceUrl returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasSourceUrl() bool {
	if o != nil && !IsNil(o.SourceUrl) {
		return true
	}

	return false
}

// SetSourceUrl gets a reference to the given string and assigns it to the SourceUrl field.
func (o *PatchedBulkDataSourceRequest) SetSourceUrl(v string) {
	o.SourceUrl = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PatchedBulkDataSourceRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedBulkDataSourceRequest) SetDescription(v string) {
	o.Description = &v
}

// GetSyncInterval returns the SyncInterval field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkDataSourceRequest) GetSyncInterval() BulkDataSourceRequestSyncInterval {
	if o == nil || IsNil(o.SyncInterval.Get()) {
		var ret BulkDataSourceRequestSyncInterval
		return ret
	}
	return *o.SyncInterval.Get()
}

// GetSyncIntervalOk returns a tuple with the SyncInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkDataSourceRequest) GetSyncIntervalOk() (*BulkDataSourceRequestSyncInterval, bool) {
	if o == nil {
		return nil, false
	}
	return o.SyncInterval.Get(), o.SyncInterval.IsSet()
}

// HasSyncInterval returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasSyncInterval() bool {
	if o != nil && o.SyncInterval.IsSet() {
		return true
	}

	return false
}

// SetSyncInterval gets a reference to the given NullableBulkDataSourceRequestSyncInterval and assigns it to the SyncInterval field.
func (o *PatchedBulkDataSourceRequest) SetSyncInterval(v BulkDataSourceRequestSyncInterval) {
	o.SyncInterval.Set(&v)
}

// SetSyncIntervalNil sets the value for SyncInterval to be an explicit nil
func (o *PatchedBulkDataSourceRequest) SetSyncIntervalNil() {
	o.SyncInterval.Set(nil)
}

// UnsetSyncInterval ensures that no value is present for SyncInterval, not even an explicit nil
func (o *PatchedBulkDataSourceRequest) UnsetSyncInterval() {
	o.SyncInterval.Unset()
}

// GetParameters returns the Parameters field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkDataSourceRequest) GetParameters() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkDataSourceRequest) GetParametersOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return &o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given interface{} and assigns it to the Parameters field.
func (o *PatchedBulkDataSourceRequest) SetParameters(v interface{}) {
	o.Parameters = v
}

// GetIgnoreRules returns the IgnoreRules field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetIgnoreRules() string {
	if o == nil || IsNil(o.IgnoreRules) {
		var ret string
		return ret
	}
	return *o.IgnoreRules
}

// GetIgnoreRulesOk returns a tuple with the IgnoreRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetIgnoreRulesOk() (*string, bool) {
	if o == nil || IsNil(o.IgnoreRules) {
		return nil, false
	}
	return o.IgnoreRules, true
}

// HasIgnoreRules returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasIgnoreRules() bool {
	if o != nil && !IsNil(o.IgnoreRules) {
		return true
	}

	return false
}

// SetIgnoreRules gets a reference to the given string and assigns it to the IgnoreRules field.
func (o *PatchedBulkDataSourceRequest) SetIgnoreRules(v string) {
	o.IgnoreRules = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkDataSourceRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkDataSourceRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *PatchedBulkDataSourceRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *PatchedBulkDataSourceRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *PatchedBulkDataSourceRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedBulkDataSourceRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedBulkDataSourceRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedBulkDataSourceRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkDataSourceRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedBulkDataSourceRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedBulkDataSourceRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o PatchedBulkDataSourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkDataSourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.SourceUrl) {
		toSerialize["source_url"] = o.SourceUrl
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.SyncInterval.IsSet() {
		toSerialize["sync_interval"] = o.SyncInterval.Get()
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if !IsNil(o.IgnoreRules) {
		toSerialize["ignore_rules"] = o.IgnoreRules
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkDataSourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkDataSourceRequest := _PatchedBulkDataSourceRequest{}

	err = json.Unmarshal(data, &varPatchedBulkDataSourceRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkDataSourceRequest(varPatchedBulkDataSourceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		delete(additionalProperties, "source_url")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "description")
		delete(additionalProperties, "sync_interval")
		delete(additionalProperties, "parameters")
		delete(additionalProperties, "ignore_rules")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkDataSourceRequest struct {
	value *PatchedBulkDataSourceRequest
	isSet bool
}

func (v NullablePatchedBulkDataSourceRequest) Get() *PatchedBulkDataSourceRequest {
	return v.value
}

func (v *NullablePatchedBulkDataSourceRequest) Set(val *PatchedBulkDataSourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkDataSourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkDataSourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkDataSourceRequest(val *PatchedBulkDataSourceRequest) *NullablePatchedBulkDataSourceRequest {
	return &NullablePatchedBulkDataSourceRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkDataSourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkDataSourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
