/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkInterfaceTemplateRequestPoeMode * `pd` - PD * `pse` - PSE
type BulkInterfaceTemplateRequestPoeMode string

// List of BulkInterfaceTemplateRequest_poe_mode
const (
	BULKINTERFACETEMPLATEREQUESTPOEMODE_PD    BulkInterfaceTemplateRequestPoeMode = "pd"
	BULKINTERFACETEMPLATEREQUESTPOEMODE_PSE   BulkInterfaceTemplateRequestPoeMode = "pse"
	BULKINTERFACETEMPLATEREQUESTPOEMODE_EMPTY BulkInterfaceTemplateRequestPoeMode = ""
)

// All allowed values of BulkInterfaceTemplateRequestPoeMode enum
var AllowedBulkInterfaceTemplateRequestPoeModeEnumValues = []BulkInterfaceTemplateRequestPoeMode{
	"pd",
	"pse",
	"",
}

func (v *BulkInterfaceTemplateRequestPoeMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkInterfaceTemplateRequestPoeMode(value)
	for _, existing := range AllowedBulkInterfaceTemplateRequestPoeModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkInterfaceTemplateRequestPoeMode", value)
}

// NewBulkInterfaceTemplateRequestPoeModeFromValue returns a pointer to a valid BulkInterfaceTemplateRequestPoeMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkInterfaceTemplateRequestPoeModeFromValue(v string) (*BulkInterfaceTemplateRequestPoeMode, error) {
	ev := BulkInterfaceTemplateRequestPoeMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkInterfaceTemplateRequestPoeMode: valid values are %v", v, AllowedBulkInterfaceTemplateRequestPoeModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkInterfaceTemplateRequestPoeMode) IsValid() bool {
	for _, existing := range AllowedBulkInterfaceTemplateRequestPoeModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkInterfaceTemplateRequest_poe_mode value
func (v BulkInterfaceTemplateRequestPoeMode) Ptr() *BulkInterfaceTemplateRequestPoeMode {
	return &v
}

type NullableBulkInterfaceTemplateRequestPoeMode struct {
	value *BulkInterfaceTemplateRequestPoeMode
	isSet bool
}

func (v NullableBulkInterfaceTemplateRequestPoeMode) Get() *BulkInterfaceTemplateRequestPoeMode {
	return v.value
}

func (v *NullableBulkInterfaceTemplateRequestPoeMode) Set(val *BulkInterfaceTemplateRequestPoeMode) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkInterfaceTemplateRequestPoeMode) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkInterfaceTemplateRequestPoeMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkInterfaceTemplateRequestPoeMode(val *BulkInterfaceTemplateRequestPoeMode) *NullableBulkInterfaceTemplateRequestPoeMode {
	return &NullableBulkInterfaceTemplateRequestPoeMode{value: val, isSet: true}
}

func (v NullableBulkInterfaceTemplateRequestPoeMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkInterfaceTemplateRequestPoeMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
