/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkFrontPortTemplateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkFrontPortTemplateRequest{}

// BulkFrontPortTemplateRequest Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)  Serializers may declare `model_clean_fields` in Meta, naming scalar model fields whose clean()-normalized values must reach the database. DRF builds a fresh instance from the validated data on create, discarding what clean() wrote.
type BulkFrontPortTemplateRequest struct {
	Id         int32                                            `json:"id"`
	DeviceType NullableBulkConsolePortTemplateRequestDeviceType `json:"device_type,omitempty"`
	ModuleType NullableBulkConsolePortTemplateRequestModuleType `json:"module_type,omitempty"`
	// {module} is accepted as a substitution for the module bay position when attached to a module type.
	Name string `json:"name"`
	// Physical label
	Label                *string                           `json:"label,omitempty"`
	Type                 BulkFrontPortRequestType          `json:"type"`
	Color                *BriefModuleBayTypeColor          `json:"color,omitempty"`
	Positions            *int32                            `json:"positions,omitempty"`
	RearPorts            []FrontPortTemplateMappingRequest `json:"rear_ports,omitempty"`
	Description          *string                           `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkFrontPortTemplateRequest BulkFrontPortTemplateRequest

// NewBulkFrontPortTemplateRequest instantiates a new BulkFrontPortTemplateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkFrontPortTemplateRequest(id int32, name string, type_ BulkFrontPortRequestType) *BulkFrontPortTemplateRequest {
	this := BulkFrontPortTemplateRequest{}
	this.Id = id
	this.Name = name
	this.Type = type_
	return &this
}

// NewBulkFrontPortTemplateRequestWithDefaults instantiates a new BulkFrontPortTemplateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkFrontPortTemplateRequestWithDefaults() *BulkFrontPortTemplateRequest {
	this := BulkFrontPortTemplateRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkFrontPortTemplateRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkFrontPortTemplateRequest) SetId(v int32) {
	o.Id = v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkFrontPortTemplateRequest) GetDeviceType() BulkConsolePortTemplateRequestDeviceType {
	if o == nil || IsNil(o.DeviceType.Get()) {
		var ret BulkConsolePortTemplateRequestDeviceType
		return ret
	}
	return *o.DeviceType.Get()
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkFrontPortTemplateRequest) GetDeviceTypeOk() (*BulkConsolePortTemplateRequestDeviceType, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceType.Get(), o.DeviceType.IsSet()
}

// HasDeviceType returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasDeviceType() bool {
	if o != nil && o.DeviceType.IsSet() {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given NullableBulkConsolePortTemplateRequestDeviceType and assigns it to the DeviceType field.
func (o *BulkFrontPortTemplateRequest) SetDeviceType(v BulkConsolePortTemplateRequestDeviceType) {
	o.DeviceType.Set(&v)
}

// SetDeviceTypeNil sets the value for DeviceType to be an explicit nil
func (o *BulkFrontPortTemplateRequest) SetDeviceTypeNil() {
	o.DeviceType.Set(nil)
}

// UnsetDeviceType ensures that no value is present for DeviceType, not even an explicit nil
func (o *BulkFrontPortTemplateRequest) UnsetDeviceType() {
	o.DeviceType.Unset()
}

// GetModuleType returns the ModuleType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkFrontPortTemplateRequest) GetModuleType() BulkConsolePortTemplateRequestModuleType {
	if o == nil || IsNil(o.ModuleType.Get()) {
		var ret BulkConsolePortTemplateRequestModuleType
		return ret
	}
	return *o.ModuleType.Get()
}

// GetModuleTypeOk returns a tuple with the ModuleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkFrontPortTemplateRequest) GetModuleTypeOk() (*BulkConsolePortTemplateRequestModuleType, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModuleType.Get(), o.ModuleType.IsSet()
}

// HasModuleType returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasModuleType() bool {
	if o != nil && o.ModuleType.IsSet() {
		return true
	}

	return false
}

// SetModuleType gets a reference to the given NullableBulkConsolePortTemplateRequestModuleType and assigns it to the ModuleType field.
func (o *BulkFrontPortTemplateRequest) SetModuleType(v BulkConsolePortTemplateRequestModuleType) {
	o.ModuleType.Set(&v)
}

// SetModuleTypeNil sets the value for ModuleType to be an explicit nil
func (o *BulkFrontPortTemplateRequest) SetModuleTypeNil() {
	o.ModuleType.Set(nil)
}

// UnsetModuleType ensures that no value is present for ModuleType, not even an explicit nil
func (o *BulkFrontPortTemplateRequest) UnsetModuleType() {
	o.ModuleType.Unset()
}

// GetName returns the Name field value
func (o *BulkFrontPortTemplateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkFrontPortTemplateRequest) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *BulkFrontPortTemplateRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *BulkFrontPortTemplateRequest) SetLabel(v string) {
	o.Label = &v
}

// GetType returns the Type field value
func (o *BulkFrontPortTemplateRequest) GetType() BulkFrontPortRequestType {
	if o == nil {
		var ret BulkFrontPortRequestType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetTypeOk() (*BulkFrontPortRequestType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BulkFrontPortTemplateRequest) SetType(v BulkFrontPortRequestType) {
	o.Type = v
}

// GetColor returns the Color field value if set, zero value otherwise.
func (o *BulkFrontPortTemplateRequest) GetColor() BriefModuleBayTypeColor {
	if o == nil || IsNil(o.Color) {
		var ret BriefModuleBayTypeColor
		return ret
	}
	return *o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetColorOk() (*BriefModuleBayTypeColor, bool) {
	if o == nil || IsNil(o.Color) {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasColor() bool {
	if o != nil && !IsNil(o.Color) {
		return true
	}

	return false
}

// SetColor gets a reference to the given BriefModuleBayTypeColor and assigns it to the Color field.
func (o *BulkFrontPortTemplateRequest) SetColor(v BriefModuleBayTypeColor) {
	o.Color = &v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *BulkFrontPortTemplateRequest) GetPositions() int32 {
	if o == nil || IsNil(o.Positions) {
		var ret int32
		return ret
	}
	return *o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetPositionsOk() (*int32, bool) {
	if o == nil || IsNil(o.Positions) {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasPositions() bool {
	if o != nil && !IsNil(o.Positions) {
		return true
	}

	return false
}

// SetPositions gets a reference to the given int32 and assigns it to the Positions field.
func (o *BulkFrontPortTemplateRequest) SetPositions(v int32) {
	o.Positions = &v
}

// GetRearPorts returns the RearPorts field value if set, zero value otherwise.
func (o *BulkFrontPortTemplateRequest) GetRearPorts() []FrontPortTemplateMappingRequest {
	if o == nil || IsNil(o.RearPorts) {
		var ret []FrontPortTemplateMappingRequest
		return ret
	}
	return o.RearPorts
}

// GetRearPortsOk returns a tuple with the RearPorts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetRearPortsOk() ([]FrontPortTemplateMappingRequest, bool) {
	if o == nil || IsNil(o.RearPorts) {
		return nil, false
	}
	return o.RearPorts, true
}

// HasRearPorts returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasRearPorts() bool {
	if o != nil && !IsNil(o.RearPorts) {
		return true
	}

	return false
}

// SetRearPorts gets a reference to the given []FrontPortTemplateMappingRequest and assigns it to the RearPorts field.
func (o *BulkFrontPortTemplateRequest) SetRearPorts(v []FrontPortTemplateMappingRequest) {
	o.RearPorts = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BulkFrontPortTemplateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkFrontPortTemplateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BulkFrontPortTemplateRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BulkFrontPortTemplateRequest) SetDescription(v string) {
	o.Description = &v
}

func (o BulkFrontPortTemplateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkFrontPortTemplateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if o.DeviceType.IsSet() {
		toSerialize["device_type"] = o.DeviceType.Get()
	}
	if o.ModuleType.IsSet() {
		toSerialize["module_type"] = o.ModuleType.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.Color) {
		toSerialize["color"] = o.Color
	}
	if !IsNil(o.Positions) {
		toSerialize["positions"] = o.Positions
	}
	if !IsNil(o.RearPorts) {
		toSerialize["rear_ports"] = o.RearPorts
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkFrontPortTemplateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"type",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBulkFrontPortTemplateRequest := _BulkFrontPortTemplateRequest{}

	err = json.Unmarshal(data, &varBulkFrontPortTemplateRequest)

	if err != nil {
		return err
	}

	*o = BulkFrontPortTemplateRequest(varBulkFrontPortTemplateRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "module_type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "type")
		delete(additionalProperties, "color")
		delete(additionalProperties, "positions")
		delete(additionalProperties, "rear_ports")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkFrontPortTemplateRequest struct {
	value *BulkFrontPortTemplateRequest
	isSet bool
}

func (v NullableBulkFrontPortTemplateRequest) Get() *BulkFrontPortTemplateRequest {
	return v.value
}

func (v *NullableBulkFrontPortTemplateRequest) Set(val *BulkFrontPortTemplateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkFrontPortTemplateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkFrontPortTemplateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkFrontPortTemplateRequest(val *BulkFrontPortTemplateRequest) *NullableBulkFrontPortTemplateRequest {
	return &NullableBulkFrontPortTemplateRequest{value: val, isSet: true}
}

func (v NullableBulkFrontPortTemplateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkFrontPortTemplateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
