/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkClusterRequestStatus * `planned` - Planned * `staging` - Staging * `active` - Active * `decommissioning` - Decommissioning * `offline` - Offline
type BulkClusterRequestStatus string

// List of BulkClusterRequest_status
const (
	BULKCLUSTERREQUESTSTATUS_PLANNED         BulkClusterRequestStatus = "planned"
	BULKCLUSTERREQUESTSTATUS_STAGING         BulkClusterRequestStatus = "staging"
	BULKCLUSTERREQUESTSTATUS_ACTIVE          BulkClusterRequestStatus = "active"
	BULKCLUSTERREQUESTSTATUS_DECOMMISSIONING BulkClusterRequestStatus = "decommissioning"
	BULKCLUSTERREQUESTSTATUS_OFFLINE         BulkClusterRequestStatus = "offline"
)

// All allowed values of BulkClusterRequestStatus enum
var AllowedBulkClusterRequestStatusEnumValues = []BulkClusterRequestStatus{
	"planned",
	"staging",
	"active",
	"decommissioning",
	"offline",
}

func (v *BulkClusterRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkClusterRequestStatus(value)
	for _, existing := range AllowedBulkClusterRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkClusterRequestStatus", value)
}

// NewBulkClusterRequestStatusFromValue returns a pointer to a valid BulkClusterRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkClusterRequestStatusFromValue(v string) (*BulkClusterRequestStatus, error) {
	ev := BulkClusterRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkClusterRequestStatus: valid values are %v", v, AllowedBulkClusterRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkClusterRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkClusterRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkClusterRequest_status value
func (v BulkClusterRequestStatus) Ptr() *BulkClusterRequestStatus {
	return &v
}

type NullableBulkClusterRequestStatus struct {
	value *BulkClusterRequestStatus
	isSet bool
}

func (v NullableBulkClusterRequestStatus) Get() *BulkClusterRequestStatus {
	return v.value
}

func (v *NullableBulkClusterRequestStatus) Set(val *BulkClusterRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkClusterRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkClusterRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkClusterRequestStatus(val *BulkClusterRequestStatus) *NullableBulkClusterRequestStatus {
	return &NullableBulkClusterRequestStatus{value: val, isSet: true}
}

func (v NullableBulkClusterRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkClusterRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
