/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkModuleBayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkModuleBayRequest{}

// BulkModuleBayRequest Adds an `owner` field for models which have a ForeignKey to users.Owner.
type BulkModuleBayRequest struct {
	Id     int32                                `json:"id"`
	Device BriefCoolingIntakeRequestDevice      `json:"device"`
	Module NullableBulkConsolePortRequestModule `json:"module,omitempty"`
	Name   string                               `json:"name"`
	// Physical label
	Label *string `json:"label,omitempty"`
	// Identifier to reference when renaming installed components
	Position             *string                              `json:"position,omitempty"`
	Enabled              *bool                                `json:"enabled,omitempty"`
	Description          *string                              `json:"description,omitempty"`
	ModuleBayTypes       []int32                              `json:"module_bay_types,omitempty"`
	InstalledModule      NullableBulkConsolePortRequestModule `json:"installed_module,omitempty"`
	Owner                NullableASNRangeRequestOwner         `json:"owner,omitempty"`
	Tags                 []NestedTagRequest                   `json:"tags,omitempty"`
	CustomFields         map[string]interface{}               `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkModuleBayRequest BulkModuleBayRequest

// NewBulkModuleBayRequest instantiates a new BulkModuleBayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkModuleBayRequest(id int32, device BriefCoolingIntakeRequestDevice, name string) *BulkModuleBayRequest {
	this := BulkModuleBayRequest{}
	this.Id = id
	this.Device = device
	this.Name = name
	return &this
}

// NewBulkModuleBayRequestWithDefaults instantiates a new BulkModuleBayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkModuleBayRequestWithDefaults() *BulkModuleBayRequest {
	this := BulkModuleBayRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkModuleBayRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkModuleBayRequest) SetId(v int32) {
	o.Id = v
}

// GetDevice returns the Device field value
func (o *BulkModuleBayRequest) GetDevice() BriefCoolingIntakeRequestDevice {
	if o == nil {
		var ret BriefCoolingIntakeRequestDevice
		return ret
	}

	return o.Device
}

// GetDeviceOk returns a tuple with the Device field value
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetDeviceOk() (*BriefCoolingIntakeRequestDevice, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Device, true
}

// SetDevice sets field value
func (o *BulkModuleBayRequest) SetDevice(v BriefCoolingIntakeRequestDevice) {
	o.Device = v
}

// GetModule returns the Module field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkModuleBayRequest) GetModule() BulkConsolePortRequestModule {
	if o == nil || IsNil(o.Module.Get()) {
		var ret BulkConsolePortRequestModule
		return ret
	}
	return *o.Module.Get()
}

// GetModuleOk returns a tuple with the Module field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkModuleBayRequest) GetModuleOk() (*BulkConsolePortRequestModule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Module.Get(), o.Module.IsSet()
}

// HasModule returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasModule() bool {
	if o != nil && o.Module.IsSet() {
		return true
	}

	return false
}

// SetModule gets a reference to the given NullableBulkConsolePortRequestModule and assigns it to the Module field.
func (o *BulkModuleBayRequest) SetModule(v BulkConsolePortRequestModule) {
	o.Module.Set(&v)
}

// SetModuleNil sets the value for Module to be an explicit nil
func (o *BulkModuleBayRequest) SetModuleNil() {
	o.Module.Set(nil)
}

// UnsetModule ensures that no value is present for Module, not even an explicit nil
func (o *BulkModuleBayRequest) UnsetModule() {
	o.Module.Unset()
}

// GetName returns the Name field value
func (o *BulkModuleBayRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkModuleBayRequest) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *BulkModuleBayRequest) SetLabel(v string) {
	o.Label = &v
}

// GetPosition returns the Position field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetPosition() string {
	if o == nil || IsNil(o.Position) {
		var ret string
		return ret
	}
	return *o.Position
}

// GetPositionOk returns a tuple with the Position field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetPositionOk() (*string, bool) {
	if o == nil || IsNil(o.Position) {
		return nil, false
	}
	return o.Position, true
}

// HasPosition returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasPosition() bool {
	if o != nil && !IsNil(o.Position) {
		return true
	}

	return false
}

// SetPosition gets a reference to the given string and assigns it to the Position field.
func (o *BulkModuleBayRequest) SetPosition(v string) {
	o.Position = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *BulkModuleBayRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BulkModuleBayRequest) SetDescription(v string) {
	o.Description = &v
}

// GetModuleBayTypes returns the ModuleBayTypes field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetModuleBayTypes() []int32 {
	if o == nil || IsNil(o.ModuleBayTypes) {
		var ret []int32
		return ret
	}
	return o.ModuleBayTypes
}

// GetModuleBayTypesOk returns a tuple with the ModuleBayTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetModuleBayTypesOk() ([]int32, bool) {
	if o == nil || IsNil(o.ModuleBayTypes) {
		return nil, false
	}
	return o.ModuleBayTypes, true
}

// HasModuleBayTypes returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasModuleBayTypes() bool {
	if o != nil && !IsNil(o.ModuleBayTypes) {
		return true
	}

	return false
}

// SetModuleBayTypes gets a reference to the given []int32 and assigns it to the ModuleBayTypes field.
func (o *BulkModuleBayRequest) SetModuleBayTypes(v []int32) {
	o.ModuleBayTypes = v
}

// GetInstalledModule returns the InstalledModule field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkModuleBayRequest) GetInstalledModule() BulkConsolePortRequestModule {
	if o == nil || IsNil(o.InstalledModule.Get()) {
		var ret BulkConsolePortRequestModule
		return ret
	}
	return *o.InstalledModule.Get()
}

// GetInstalledModuleOk returns a tuple with the InstalledModule field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkModuleBayRequest) GetInstalledModuleOk() (*BulkConsolePortRequestModule, bool) {
	if o == nil {
		return nil, false
	}
	return o.InstalledModule.Get(), o.InstalledModule.IsSet()
}

// HasInstalledModule returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasInstalledModule() bool {
	if o != nil && o.InstalledModule.IsSet() {
		return true
	}

	return false
}

// SetInstalledModule gets a reference to the given NullableBulkConsolePortRequestModule and assigns it to the InstalledModule field.
func (o *BulkModuleBayRequest) SetInstalledModule(v BulkConsolePortRequestModule) {
	o.InstalledModule.Set(&v)
}

// SetInstalledModuleNil sets the value for InstalledModule to be an explicit nil
func (o *BulkModuleBayRequest) SetInstalledModuleNil() {
	o.InstalledModule.Set(nil)
}

// UnsetInstalledModule ensures that no value is present for InstalledModule, not even an explicit nil
func (o *BulkModuleBayRequest) UnsetInstalledModule() {
	o.InstalledModule.Unset()
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkModuleBayRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkModuleBayRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *BulkModuleBayRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *BulkModuleBayRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *BulkModuleBayRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *BulkModuleBayRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *BulkModuleBayRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkModuleBayRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *BulkModuleBayRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *BulkModuleBayRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o BulkModuleBayRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkModuleBayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["device"] = o.Device
	if o.Module.IsSet() {
		toSerialize["module"] = o.Module.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Position) {
		toSerialize["position"] = o.Position
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ModuleBayTypes) {
		toSerialize["module_bay_types"] = o.ModuleBayTypes
	}
	if o.InstalledModule.IsSet() {
		toSerialize["installed_module"] = o.InstalledModule.Get()
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkModuleBayRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"device",
		"name",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBulkModuleBayRequest := _BulkModuleBayRequest{}

	err = json.Unmarshal(data, &varBulkModuleBayRequest)

	if err != nil {
		return err
	}

	*o = BulkModuleBayRequest(varBulkModuleBayRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "device")
		delete(additionalProperties, "module")
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "position")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "description")
		delete(additionalProperties, "module_bay_types")
		delete(additionalProperties, "installed_module")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkModuleBayRequest struct {
	value *BulkModuleBayRequest
	isSet bool
}

func (v NullableBulkModuleBayRequest) Get() *BulkModuleBayRequest {
	return v.value
}

func (v *NullableBulkModuleBayRequest) Set(val *BulkModuleBayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkModuleBayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkModuleBayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkModuleBayRequest(val *BulkModuleBayRequest) *NullableBulkModuleBayRequest {
	return &NullableBulkModuleBayRequest{value: val, isSet: true}
}

func (v NullableBulkModuleBayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkModuleBayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
