/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the CoolingOutflowTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CoolingOutflowTemplate{}

// CoolingOutflowTemplate Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)  Serializers may declare `model_clean_fields` in Meta, naming scalar model fields whose clean()-normalized values must reach the database. DRF builds a fresh instance from the validated data on create, discarding what clean() wrote.
type CoolingOutflowTemplate struct {
	Id         int32                   `json:"id"`
	Url        string                  `json:"url"`
	Display    string                  `json:"display"`
	DeviceType NullableBriefDeviceType `json:"device_type,omitempty"`
	ModuleType NullableBriefModuleType `json:"module_type,omitempty"`
	// {module} is accepted as a substitution for the module bay position when attached to a module type.
	Name string `json:"name"`
	// Physical label
	Label                *string                            `json:"label,omitempty"`
	Type                 NullableCoolingIntakeType          `json:"type,omitempty"`
	Diameter             NullableFloat64                    `json:"diameter,omitempty"`
	DiameterUnit         NullableCoolingIntakeDiameterUnit  `json:"diameter_unit,omitempty"`
	CoolingIntake        NullableBriefCoolingIntakeTemplate `json:"cooling_intake,omitempty"`
	Description          *string                            `json:"description,omitempty"`
	Created              NullableTime                       `json:"created"`
	LastUpdated          NullableTime                       `json:"last_updated"`
	AdditionalProperties map[string]interface{}
}

type _CoolingOutflowTemplate CoolingOutflowTemplate

// NewCoolingOutflowTemplate instantiates a new CoolingOutflowTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoolingOutflowTemplate(id int32, url string, display string, name string, created NullableTime, lastUpdated NullableTime) *CoolingOutflowTemplate {
	this := CoolingOutflowTemplate{}
	this.Id = id
	this.Url = url
	this.Display = display
	this.Name = name
	this.Created = created
	this.LastUpdated = lastUpdated
	return &this
}

// NewCoolingOutflowTemplateWithDefaults instantiates a new CoolingOutflowTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoolingOutflowTemplateWithDefaults() *CoolingOutflowTemplate {
	this := CoolingOutflowTemplate{}
	return &this
}

// GetId returns the Id field value
func (o *CoolingOutflowTemplate) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CoolingOutflowTemplate) SetId(v int32) {
	o.Id = v
}

// GetUrl returns the Url field value
func (o *CoolingOutflowTemplate) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *CoolingOutflowTemplate) SetUrl(v string) {
	o.Url = v
}

// GetDisplay returns the Display field value
func (o *CoolingOutflowTemplate) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *CoolingOutflowTemplate) SetDisplay(v string) {
	o.Display = v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetDeviceType() BriefDeviceType {
	if o == nil || IsNil(o.DeviceType.Get()) {
		var ret BriefDeviceType
		return ret
	}
	return *o.DeviceType.Get()
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetDeviceTypeOk() (*BriefDeviceType, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceType.Get(), o.DeviceType.IsSet()
}

// HasDeviceType returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasDeviceType() bool {
	if o != nil && o.DeviceType.IsSet() {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given NullableBriefDeviceType and assigns it to the DeviceType field.
func (o *CoolingOutflowTemplate) SetDeviceType(v BriefDeviceType) {
	o.DeviceType.Set(&v)
}

// SetDeviceTypeNil sets the value for DeviceType to be an explicit nil
func (o *CoolingOutflowTemplate) SetDeviceTypeNil() {
	o.DeviceType.Set(nil)
}

// UnsetDeviceType ensures that no value is present for DeviceType, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetDeviceType() {
	o.DeviceType.Unset()
}

// GetModuleType returns the ModuleType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetModuleType() BriefModuleType {
	if o == nil || IsNil(o.ModuleType.Get()) {
		var ret BriefModuleType
		return ret
	}
	return *o.ModuleType.Get()
}

// GetModuleTypeOk returns a tuple with the ModuleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetModuleTypeOk() (*BriefModuleType, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModuleType.Get(), o.ModuleType.IsSet()
}

// HasModuleType returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasModuleType() bool {
	if o != nil && o.ModuleType.IsSet() {
		return true
	}

	return false
}

// SetModuleType gets a reference to the given NullableBriefModuleType and assigns it to the ModuleType field.
func (o *CoolingOutflowTemplate) SetModuleType(v BriefModuleType) {
	o.ModuleType.Set(&v)
}

// SetModuleTypeNil sets the value for ModuleType to be an explicit nil
func (o *CoolingOutflowTemplate) SetModuleTypeNil() {
	o.ModuleType.Set(nil)
}

// UnsetModuleType ensures that no value is present for ModuleType, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetModuleType() {
	o.ModuleType.Unset()
}

// GetName returns the Name field value
func (o *CoolingOutflowTemplate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CoolingOutflowTemplate) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CoolingOutflowTemplate) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CoolingOutflowTemplate) SetLabel(v string) {
	o.Label = &v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetType() CoolingIntakeType {
	if o == nil || IsNil(o.Type.Get()) {
		var ret CoolingIntakeType
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetTypeOk() (*CoolingIntakeType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableCoolingIntakeType and assigns it to the Type field.
func (o *CoolingOutflowTemplate) SetType(v CoolingIntakeType) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *CoolingOutflowTemplate) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetType() {
	o.Type.Unset()
}

// GetDiameter returns the Diameter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetDiameter() float64 {
	if o == nil || IsNil(o.Diameter.Get()) {
		var ret float64
		return ret
	}
	return *o.Diameter.Get()
}

// GetDiameterOk returns a tuple with the Diameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetDiameterOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Diameter.Get(), o.Diameter.IsSet()
}

// HasDiameter returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasDiameter() bool {
	if o != nil && o.Diameter.IsSet() {
		return true
	}

	return false
}

// SetDiameter gets a reference to the given NullableFloat64 and assigns it to the Diameter field.
func (o *CoolingOutflowTemplate) SetDiameter(v float64) {
	o.Diameter.Set(&v)
}

// SetDiameterNil sets the value for Diameter to be an explicit nil
func (o *CoolingOutflowTemplate) SetDiameterNil() {
	o.Diameter.Set(nil)
}

// UnsetDiameter ensures that no value is present for Diameter, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetDiameter() {
	o.Diameter.Unset()
}

// GetDiameterUnit returns the DiameterUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetDiameterUnit() CoolingIntakeDiameterUnit {
	if o == nil || IsNil(o.DiameterUnit.Get()) {
		var ret CoolingIntakeDiameterUnit
		return ret
	}
	return *o.DiameterUnit.Get()
}

// GetDiameterUnitOk returns a tuple with the DiameterUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetDiameterUnitOk() (*CoolingIntakeDiameterUnit, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiameterUnit.Get(), o.DiameterUnit.IsSet()
}

// HasDiameterUnit returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasDiameterUnit() bool {
	if o != nil && o.DiameterUnit.IsSet() {
		return true
	}

	return false
}

// SetDiameterUnit gets a reference to the given NullableCoolingIntakeDiameterUnit and assigns it to the DiameterUnit field.
func (o *CoolingOutflowTemplate) SetDiameterUnit(v CoolingIntakeDiameterUnit) {
	o.DiameterUnit.Set(&v)
}

// SetDiameterUnitNil sets the value for DiameterUnit to be an explicit nil
func (o *CoolingOutflowTemplate) SetDiameterUnitNil() {
	o.DiameterUnit.Set(nil)
}

// UnsetDiameterUnit ensures that no value is present for DiameterUnit, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetDiameterUnit() {
	o.DiameterUnit.Unset()
}

// GetCoolingIntake returns the CoolingIntake field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CoolingOutflowTemplate) GetCoolingIntake() BriefCoolingIntakeTemplate {
	if o == nil || IsNil(o.CoolingIntake.Get()) {
		var ret BriefCoolingIntakeTemplate
		return ret
	}
	return *o.CoolingIntake.Get()
}

// GetCoolingIntakeOk returns a tuple with the CoolingIntake field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetCoolingIntakeOk() (*BriefCoolingIntakeTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return o.CoolingIntake.Get(), o.CoolingIntake.IsSet()
}

// HasCoolingIntake returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasCoolingIntake() bool {
	if o != nil && o.CoolingIntake.IsSet() {
		return true
	}

	return false
}

// SetCoolingIntake gets a reference to the given NullableBriefCoolingIntakeTemplate and assigns it to the CoolingIntake field.
func (o *CoolingOutflowTemplate) SetCoolingIntake(v BriefCoolingIntakeTemplate) {
	o.CoolingIntake.Set(&v)
}

// SetCoolingIntakeNil sets the value for CoolingIntake to be an explicit nil
func (o *CoolingOutflowTemplate) SetCoolingIntakeNil() {
	o.CoolingIntake.Set(nil)
}

// UnsetCoolingIntake ensures that no value is present for CoolingIntake, not even an explicit nil
func (o *CoolingOutflowTemplate) UnsetCoolingIntake() {
	o.CoolingIntake.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CoolingOutflowTemplate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoolingOutflowTemplate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CoolingOutflowTemplate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CoolingOutflowTemplate) SetDescription(v string) {
	o.Description = &v
}

// GetCreated returns the Created field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *CoolingOutflowTemplate) GetCreated() time.Time {
	if o == nil || o.Created.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// SetCreated sets field value
func (o *CoolingOutflowTemplate) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// GetLastUpdated returns the LastUpdated field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *CoolingOutflowTemplate) GetLastUpdated() time.Time {
	if o == nil || o.LastUpdated.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CoolingOutflowTemplate) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// SetLastUpdated sets field value
func (o *CoolingOutflowTemplate) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

func (o CoolingOutflowTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CoolingOutflowTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["url"] = o.Url
	toSerialize["display"] = o.Display
	if o.DeviceType.IsSet() {
		toSerialize["device_type"] = o.DeviceType.Get()
	}
	if o.ModuleType.IsSet() {
		toSerialize["module_type"] = o.ModuleType.Get()
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.Diameter.IsSet() {
		toSerialize["diameter"] = o.Diameter.Get()
	}
	if o.DiameterUnit.IsSet() {
		toSerialize["diameter_unit"] = o.DiameterUnit.Get()
	}
	if o.CoolingIntake.IsSet() {
		toSerialize["cooling_intake"] = o.CoolingIntake.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["created"] = o.Created.Get()
	toSerialize["last_updated"] = o.LastUpdated.Get()

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CoolingOutflowTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"url",
		"display",
		"name",
		"created",
		"last_updated",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varCoolingOutflowTemplate := _CoolingOutflowTemplate{}

	err = json.Unmarshal(data, &varCoolingOutflowTemplate)

	if err != nil {
		return err
	}

	*o = CoolingOutflowTemplate(varCoolingOutflowTemplate)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "url")
		delete(additionalProperties, "display")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "module_type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "type")
		delete(additionalProperties, "diameter")
		delete(additionalProperties, "diameter_unit")
		delete(additionalProperties, "cooling_intake")
		delete(additionalProperties, "description")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCoolingOutflowTemplate struct {
	value *CoolingOutflowTemplate
	isSet bool
}

func (v NullableCoolingOutflowTemplate) Get() *CoolingOutflowTemplate {
	return v.value
}

func (v *NullableCoolingOutflowTemplate) Set(val *CoolingOutflowTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableCoolingOutflowTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableCoolingOutflowTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoolingOutflowTemplate(val *CoolingOutflowTemplate) *NullableCoolingOutflowTemplate {
	return &NullableCoolingOutflowTemplate{value: val, isSet: true}
}

func (v NullableCoolingOutflowTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoolingOutflowTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
