/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkCircuitGroupAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkCircuitGroupAssignmentRequest{}

// BulkCircuitGroupAssignmentRequest Base serializer for group assignments under CircuitSerializer.
type BulkCircuitGroupAssignmentRequest struct {
	Id                   int32                                               `json:"id"`
	Group                BriefCircuitGroupAssignmentSerializerRequestGroup   `json:"group"`
	MemberType           string                                              `json:"member_type"`
	MemberId             int64                                               `json:"member_id"`
	Priority             *BriefCircuitGroupAssignmentSerializerPriorityValue `json:"priority,omitempty"`
	Tags                 []NestedTagRequest                                  `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkCircuitGroupAssignmentRequest BulkCircuitGroupAssignmentRequest

// NewBulkCircuitGroupAssignmentRequest instantiates a new BulkCircuitGroupAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCircuitGroupAssignmentRequest(id int32, group BriefCircuitGroupAssignmentSerializerRequestGroup, memberType string, memberId int64) *BulkCircuitGroupAssignmentRequest {
	this := BulkCircuitGroupAssignmentRequest{}
	this.Id = id
	this.Group = group
	this.MemberType = memberType
	this.MemberId = memberId
	return &this
}

// NewBulkCircuitGroupAssignmentRequestWithDefaults instantiates a new BulkCircuitGroupAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCircuitGroupAssignmentRequestWithDefaults() *BulkCircuitGroupAssignmentRequest {
	this := BulkCircuitGroupAssignmentRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkCircuitGroupAssignmentRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkCircuitGroupAssignmentRequest) SetId(v int32) {
	o.Id = v
}

// GetGroup returns the Group field value
func (o *BulkCircuitGroupAssignmentRequest) GetGroup() BriefCircuitGroupAssignmentSerializerRequestGroup {
	if o == nil {
		var ret BriefCircuitGroupAssignmentSerializerRequestGroup
		return ret
	}

	return o.Group
}

// GetGroupOk returns a tuple with the Group field value
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetGroupOk() (*BriefCircuitGroupAssignmentSerializerRequestGroup, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Group, true
}

// SetGroup sets field value
func (o *BulkCircuitGroupAssignmentRequest) SetGroup(v BriefCircuitGroupAssignmentSerializerRequestGroup) {
	o.Group = v
}

// GetMemberType returns the MemberType field value
func (o *BulkCircuitGroupAssignmentRequest) GetMemberType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemberType
}

// GetMemberTypeOk returns a tuple with the MemberType field value
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetMemberTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberType, true
}

// SetMemberType sets field value
func (o *BulkCircuitGroupAssignmentRequest) SetMemberType(v string) {
	o.MemberType = v
}

// GetMemberId returns the MemberId field value
func (o *BulkCircuitGroupAssignmentRequest) GetMemberId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.MemberId
}

// GetMemberIdOk returns a tuple with the MemberId field value
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetMemberIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemberId, true
}

// SetMemberId sets field value
func (o *BulkCircuitGroupAssignmentRequest) SetMemberId(v int64) {
	o.MemberId = v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *BulkCircuitGroupAssignmentRequest) GetPriority() BriefCircuitGroupAssignmentSerializerPriorityValue {
	if o == nil || IsNil(o.Priority) {
		var ret BriefCircuitGroupAssignmentSerializerPriorityValue
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetPriorityOk() (*BriefCircuitGroupAssignmentSerializerPriorityValue, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *BulkCircuitGroupAssignmentRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given BriefCircuitGroupAssignmentSerializerPriorityValue and assigns it to the Priority field.
func (o *BulkCircuitGroupAssignmentRequest) SetPriority(v BriefCircuitGroupAssignmentSerializerPriorityValue) {
	o.Priority = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BulkCircuitGroupAssignmentRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCircuitGroupAssignmentRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BulkCircuitGroupAssignmentRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *BulkCircuitGroupAssignmentRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

func (o BulkCircuitGroupAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkCircuitGroupAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["group"] = o.Group
	toSerialize["member_type"] = o.MemberType
	toSerialize["member_id"] = o.MemberId
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkCircuitGroupAssignmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"group",
		"member_type",
		"member_id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varBulkCircuitGroupAssignmentRequest := _BulkCircuitGroupAssignmentRequest{}

	err = json.Unmarshal(data, &varBulkCircuitGroupAssignmentRequest)

	if err != nil {
		return err
	}

	*o = BulkCircuitGroupAssignmentRequest(varBulkCircuitGroupAssignmentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "group")
		delete(additionalProperties, "member_type")
		delete(additionalProperties, "member_id")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkCircuitGroupAssignmentRequest struct {
	value *BulkCircuitGroupAssignmentRequest
	isSet bool
}

func (v NullableBulkCircuitGroupAssignmentRequest) Get() *BulkCircuitGroupAssignmentRequest {
	return v.value
}

func (v *NullableBulkCircuitGroupAssignmentRequest) Set(val *BulkCircuitGroupAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCircuitGroupAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCircuitGroupAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCircuitGroupAssignmentRequest(val *BulkCircuitGroupAssignmentRequest) *NullableBulkCircuitGroupAssignmentRequest {
	return &NullableBulkCircuitGroupAssignmentRequest{value: val, isSet: true}
}

func (v NullableBulkCircuitGroupAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCircuitGroupAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
