/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkCircuitRequestDistanceUnit * `km` - Kilometers * `m` - Meters * `mi` - Miles * `ft` - Feet
type BulkCircuitRequestDistanceUnit string

// List of BulkCircuitRequest_distance_unit
const (
	BULKCIRCUITREQUESTDISTANCEUNIT_KM    BulkCircuitRequestDistanceUnit = "km"
	BULKCIRCUITREQUESTDISTANCEUNIT_M     BulkCircuitRequestDistanceUnit = "m"
	BULKCIRCUITREQUESTDISTANCEUNIT_MI    BulkCircuitRequestDistanceUnit = "mi"
	BULKCIRCUITREQUESTDISTANCEUNIT_FT    BulkCircuitRequestDistanceUnit = "ft"
	BULKCIRCUITREQUESTDISTANCEUNIT_EMPTY BulkCircuitRequestDistanceUnit = ""
)

// All allowed values of BulkCircuitRequestDistanceUnit enum
var AllowedBulkCircuitRequestDistanceUnitEnumValues = []BulkCircuitRequestDistanceUnit{
	"km",
	"m",
	"mi",
	"ft",
	"",
}

func (v *BulkCircuitRequestDistanceUnit) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkCircuitRequestDistanceUnit(value)
	for _, existing := range AllowedBulkCircuitRequestDistanceUnitEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkCircuitRequestDistanceUnit", value)
}

// NewBulkCircuitRequestDistanceUnitFromValue returns a pointer to a valid BulkCircuitRequestDistanceUnit
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkCircuitRequestDistanceUnitFromValue(v string) (*BulkCircuitRequestDistanceUnit, error) {
	ev := BulkCircuitRequestDistanceUnit(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkCircuitRequestDistanceUnit: valid values are %v", v, AllowedBulkCircuitRequestDistanceUnitEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkCircuitRequestDistanceUnit) IsValid() bool {
	for _, existing := range AllowedBulkCircuitRequestDistanceUnitEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkCircuitRequest_distance_unit value
func (v BulkCircuitRequestDistanceUnit) Ptr() *BulkCircuitRequestDistanceUnit {
	return &v
}

type NullableBulkCircuitRequestDistanceUnit struct {
	value *BulkCircuitRequestDistanceUnit
	isSet bool
}

func (v NullableBulkCircuitRequestDistanceUnit) Get() *BulkCircuitRequestDistanceUnit {
	return v.value
}

func (v *NullableBulkCircuitRequestDistanceUnit) Set(val *BulkCircuitRequestDistanceUnit) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCircuitRequestDistanceUnit) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCircuitRequestDistanceUnit) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCircuitRequestDistanceUnit(val *BulkCircuitRequestDistanceUnit) *NullableBulkCircuitRequestDistanceUnit {
	return &NullableBulkCircuitRequestDistanceUnit{value: val, isSet: true}
}

func (v NullableBulkCircuitRequestDistanceUnit) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCircuitRequestDistanceUnit) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
