/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkCircuitGroupAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkCircuitGroupAssignmentRequest{}

// PatchedBulkCircuitGroupAssignmentRequest Base serializer for group assignments under CircuitSerializer.
type PatchedBulkCircuitGroupAssignmentRequest struct {
	Id                   int32                                               `json:"id"`
	Group                *BriefCircuitGroupAssignmentSerializerRequestGroup  `json:"group,omitempty"`
	MemberType           *string                                             `json:"member_type,omitempty"`
	MemberId             *int64                                              `json:"member_id,omitempty"`
	Priority             *BriefCircuitGroupAssignmentSerializerPriorityValue `json:"priority,omitempty"`
	Tags                 []NestedTagRequest                                  `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkCircuitGroupAssignmentRequest PatchedBulkCircuitGroupAssignmentRequest

// NewPatchedBulkCircuitGroupAssignmentRequest instantiates a new PatchedBulkCircuitGroupAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkCircuitGroupAssignmentRequest(id int32) *PatchedBulkCircuitGroupAssignmentRequest {
	this := PatchedBulkCircuitGroupAssignmentRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkCircuitGroupAssignmentRequestWithDefaults instantiates a new PatchedBulkCircuitGroupAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkCircuitGroupAssignmentRequestWithDefaults() *PatchedBulkCircuitGroupAssignmentRequest {
	this := PatchedBulkCircuitGroupAssignmentRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetId(v int32) {
	o.Id = v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetGroup() BriefCircuitGroupAssignmentSerializerRequestGroup {
	if o == nil || IsNil(o.Group) {
		var ret BriefCircuitGroupAssignmentSerializerRequestGroup
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetGroupOk() (*BriefCircuitGroupAssignmentSerializerRequestGroup, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given BriefCircuitGroupAssignmentSerializerRequestGroup and assigns it to the Group field.
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetGroup(v BriefCircuitGroupAssignmentSerializerRequestGroup) {
	o.Group = &v
}

// GetMemberType returns the MemberType field value if set, zero value otherwise.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetMemberType() string {
	if o == nil || IsNil(o.MemberType) {
		var ret string
		return ret
	}
	return *o.MemberType
}

// GetMemberTypeOk returns a tuple with the MemberType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetMemberTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MemberType) {
		return nil, false
	}
	return o.MemberType, true
}

// HasMemberType returns a boolean if a field has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) HasMemberType() bool {
	if o != nil && !IsNil(o.MemberType) {
		return true
	}

	return false
}

// SetMemberType gets a reference to the given string and assigns it to the MemberType field.
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetMemberType(v string) {
	o.MemberType = &v
}

// GetMemberId returns the MemberId field value if set, zero value otherwise.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetMemberId() int64 {
	if o == nil || IsNil(o.MemberId) {
		var ret int64
		return ret
	}
	return *o.MemberId
}

// GetMemberIdOk returns a tuple with the MemberId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetMemberIdOk() (*int64, bool) {
	if o == nil || IsNil(o.MemberId) {
		return nil, false
	}
	return o.MemberId, true
}

// HasMemberId returns a boolean if a field has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) HasMemberId() bool {
	if o != nil && !IsNil(o.MemberId) {
		return true
	}

	return false
}

// SetMemberId gets a reference to the given int64 and assigns it to the MemberId field.
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetMemberId(v int64) {
	o.MemberId = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetPriority() BriefCircuitGroupAssignmentSerializerPriorityValue {
	if o == nil || IsNil(o.Priority) {
		var ret BriefCircuitGroupAssignmentSerializerPriorityValue
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetPriorityOk() (*BriefCircuitGroupAssignmentSerializerPriorityValue, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given BriefCircuitGroupAssignmentSerializerPriorityValue and assigns it to the Priority field.
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetPriority(v BriefCircuitGroupAssignmentSerializerPriorityValue) {
	o.Priority = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkCircuitGroupAssignmentRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedBulkCircuitGroupAssignmentRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

func (o PatchedBulkCircuitGroupAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkCircuitGroupAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	if !IsNil(o.MemberType) {
		toSerialize["member_type"] = o.MemberType
	}
	if !IsNil(o.MemberId) {
		toSerialize["member_id"] = o.MemberId
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkCircuitGroupAssignmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkCircuitGroupAssignmentRequest := _PatchedBulkCircuitGroupAssignmentRequest{}

	err = json.Unmarshal(data, &varPatchedBulkCircuitGroupAssignmentRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkCircuitGroupAssignmentRequest(varPatchedBulkCircuitGroupAssignmentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "group")
		delete(additionalProperties, "member_type")
		delete(additionalProperties, "member_id")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkCircuitGroupAssignmentRequest struct {
	value *PatchedBulkCircuitGroupAssignmentRequest
	isSet bool
}

func (v NullablePatchedBulkCircuitGroupAssignmentRequest) Get() *PatchedBulkCircuitGroupAssignmentRequest {
	return v.value
}

func (v *NullablePatchedBulkCircuitGroupAssignmentRequest) Set(val *PatchedBulkCircuitGroupAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkCircuitGroupAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkCircuitGroupAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkCircuitGroupAssignmentRequest(val *PatchedBulkCircuitGroupAssignmentRequest) *NullablePatchedBulkCircuitGroupAssignmentRequest {
	return &NullablePatchedBulkCircuitGroupAssignmentRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkCircuitGroupAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkCircuitGroupAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
