/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// DcimCableBundlesCreateRequest - struct for DcimCableBundlesCreateRequest
type DcimCableBundlesCreateRequest struct {
	CableBundleRequest        *CableBundleRequest
	ArrayOfCableBundleRequest *[]CableBundleRequest
}

// CableBundleRequestAsDcimCableBundlesCreateRequest is a convenience function that returns CableBundleRequest wrapped in DcimCableBundlesCreateRequest
func CableBundleRequestAsDcimCableBundlesCreateRequest(v *CableBundleRequest) DcimCableBundlesCreateRequest {
	return DcimCableBundlesCreateRequest{
		CableBundleRequest: v,
	}
}

// []CableBundleRequestAsDcimCableBundlesCreateRequest is a convenience function that returns []CableBundleRequest wrapped in DcimCableBundlesCreateRequest
func ArrayOfCableBundleRequestAsDcimCableBundlesCreateRequest(v *[]CableBundleRequest) DcimCableBundlesCreateRequest {
	return DcimCableBundlesCreateRequest{
		ArrayOfCableBundleRequest: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *DcimCableBundlesCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CableBundleRequest
	err = newStrictDecoder(data).Decode(&dst.CableBundleRequest)
	if err == nil {
		jsonCableBundleRequest, _ := json.Marshal(dst.CableBundleRequest)
		if string(jsonCableBundleRequest) == "{}" { // empty struct
			dst.CableBundleRequest = nil
		} else {
			if err = validator.Validate(dst.CableBundleRequest); err != nil {
				dst.CableBundleRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.CableBundleRequest = nil
	}

	// try to unmarshal data into ArrayOfCableBundleRequest
	err = newStrictDecoder(data).Decode(&dst.ArrayOfCableBundleRequest)
	if err == nil {
		jsonArrayOfCableBundleRequest, _ := json.Marshal(dst.ArrayOfCableBundleRequest)
		if string(jsonArrayOfCableBundleRequest) == "{}" { // empty struct
			dst.ArrayOfCableBundleRequest = nil
		} else {
			if err = validator.Validate(dst.ArrayOfCableBundleRequest); err != nil {
				dst.ArrayOfCableBundleRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ArrayOfCableBundleRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CableBundleRequest = nil
		dst.ArrayOfCableBundleRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DcimCableBundlesCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(DcimCableBundlesCreateRequest): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(DcimCableBundlesCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DcimCableBundlesCreateRequest) MarshalJSON() ([]byte, error) {
	if src.CableBundleRequest != nil {
		return json.Marshal(&src.CableBundleRequest)
	}

	if src.ArrayOfCableBundleRequest != nil {
		return json.Marshal(&src.ArrayOfCableBundleRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DcimCableBundlesCreateRequest) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CableBundleRequest != nil {
		return obj.CableBundleRequest
	}

	if obj.ArrayOfCableBundleRequest != nil {
		return obj.ArrayOfCableBundleRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DcimCableBundlesCreateRequest) GetActualInstanceValue() interface{} {
	if obj.CableBundleRequest != nil {
		return *obj.CableBundleRequest
	}

	if obj.ArrayOfCableBundleRequest != nil {
		return *obj.ArrayOfCableBundleRequest
	}

	// all schemas are nil
	return nil
}

type NullableDcimCableBundlesCreateRequest struct {
	value *DcimCableBundlesCreateRequest
	isSet bool
}

func (v NullableDcimCableBundlesCreateRequest) Get() *DcimCableBundlesCreateRequest {
	return v.value
}

func (v *NullableDcimCableBundlesCreateRequest) Set(val *DcimCableBundlesCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDcimCableBundlesCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDcimCableBundlesCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDcimCableBundlesCreateRequest(val *DcimCableBundlesCreateRequest) *NullableDcimCableBundlesCreateRequest {
	return &NullableDcimCableBundlesCreateRequest{value: val, isSet: true}
}

func (v NullableDcimCableBundlesCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDcimCableBundlesCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
