/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkVMInterfaceRequestVirtualMachine - struct for BulkVMInterfaceRequestVirtualMachine
type BulkVMInterfaceRequestVirtualMachine struct {
	BriefVirtualMachineRequest *BriefVirtualMachineRequest
	Int32                      *int32
}

// BriefVirtualMachineRequestAsBulkVMInterfaceRequestVirtualMachine is a convenience function that returns BriefVirtualMachineRequest wrapped in BulkVMInterfaceRequestVirtualMachine
func BriefVirtualMachineRequestAsBulkVMInterfaceRequestVirtualMachine(v *BriefVirtualMachineRequest) BulkVMInterfaceRequestVirtualMachine {
	return BulkVMInterfaceRequestVirtualMachine{
		BriefVirtualMachineRequest: v,
	}
}

// int32AsBulkVMInterfaceRequestVirtualMachine is a convenience function that returns int32 wrapped in BulkVMInterfaceRequestVirtualMachine
func Int32AsBulkVMInterfaceRequestVirtualMachine(v *int32) BulkVMInterfaceRequestVirtualMachine {
	return BulkVMInterfaceRequestVirtualMachine{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkVMInterfaceRequestVirtualMachine) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefVirtualMachineRequest
	err = newStrictDecoder(data).Decode(&dst.BriefVirtualMachineRequest)
	if err == nil {
		jsonBriefVirtualMachineRequest, _ := json.Marshal(dst.BriefVirtualMachineRequest)
		if string(jsonBriefVirtualMachineRequest) == "{}" { // empty struct
			dst.BriefVirtualMachineRequest = nil
		} else {
			if err = validator.Validate(dst.BriefVirtualMachineRequest); err != nil {
				dst.BriefVirtualMachineRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefVirtualMachineRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefVirtualMachineRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkVMInterfaceRequestVirtualMachine)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVMInterfaceRequestVirtualMachine): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(BulkVMInterfaceRequestVirtualMachine)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkVMInterfaceRequestVirtualMachine) MarshalJSON() ([]byte, error) {
	if src.BriefVirtualMachineRequest != nil {
		return json.Marshal(&src.BriefVirtualMachineRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkVMInterfaceRequestVirtualMachine) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefVirtualMachineRequest != nil {
		return obj.BriefVirtualMachineRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkVMInterfaceRequestVirtualMachine) GetActualInstanceValue() interface{} {
	if obj.BriefVirtualMachineRequest != nil {
		return *obj.BriefVirtualMachineRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkVMInterfaceRequestVirtualMachine struct {
	value *BulkVMInterfaceRequestVirtualMachine
	isSet bool
}

func (v NullableBulkVMInterfaceRequestVirtualMachine) Get() *BulkVMInterfaceRequestVirtualMachine {
	return v.value
}

func (v *NullableBulkVMInterfaceRequestVirtualMachine) Set(val *BulkVMInterfaceRequestVirtualMachine) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVMInterfaceRequestVirtualMachine) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVMInterfaceRequestVirtualMachine) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVMInterfaceRequestVirtualMachine(val *BulkVMInterfaceRequestVirtualMachine) *NullableBulkVMInterfaceRequestVirtualMachine {
	return &NullableBulkVMInterfaceRequestVirtualMachine{value: val, isSet: true}
}

func (v NullableBulkVMInterfaceRequestVirtualMachine) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVMInterfaceRequestVirtualMachine) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
