/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BriefCoolingIntakeRequestDevice - struct for BriefCoolingIntakeRequestDevice
type BriefCoolingIntakeRequestDevice struct {
	BriefDeviceRequest *BriefDeviceRequest
	Int32              *int32
}

// BriefDeviceRequestAsBriefCoolingIntakeRequestDevice is a convenience function that returns BriefDeviceRequest wrapped in BriefCoolingIntakeRequestDevice
func BriefDeviceRequestAsBriefCoolingIntakeRequestDevice(v *BriefDeviceRequest) BriefCoolingIntakeRequestDevice {
	return BriefCoolingIntakeRequestDevice{
		BriefDeviceRequest: v,
	}
}

// int32AsBriefCoolingIntakeRequestDevice is a convenience function that returns int32 wrapped in BriefCoolingIntakeRequestDevice
func Int32AsBriefCoolingIntakeRequestDevice(v *int32) BriefCoolingIntakeRequestDevice {
	return BriefCoolingIntakeRequestDevice{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BriefCoolingIntakeRequestDevice) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BriefDeviceRequest
	err = newStrictDecoder(data).Decode(&dst.BriefDeviceRequest)
	if err == nil {
		jsonBriefDeviceRequest, _ := json.Marshal(dst.BriefDeviceRequest)
		if string(jsonBriefDeviceRequest) == "{}" { // empty struct
			dst.BriefDeviceRequest = nil
		} else {
			if err = validator.Validate(dst.BriefDeviceRequest); err != nil {
				dst.BriefDeviceRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefDeviceRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefDeviceRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BriefCoolingIntakeRequestDevice)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BriefCoolingIntakeRequestDevice): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(BriefCoolingIntakeRequestDevice)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BriefCoolingIntakeRequestDevice) MarshalJSON() ([]byte, error) {
	if src.BriefDeviceRequest != nil {
		return json.Marshal(&src.BriefDeviceRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BriefCoolingIntakeRequestDevice) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefDeviceRequest != nil {
		return obj.BriefDeviceRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BriefCoolingIntakeRequestDevice) GetActualInstanceValue() interface{} {
	if obj.BriefDeviceRequest != nil {
		return *obj.BriefDeviceRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBriefCoolingIntakeRequestDevice struct {
	value *BriefCoolingIntakeRequestDevice
	isSet bool
}

func (v NullableBriefCoolingIntakeRequestDevice) Get() *BriefCoolingIntakeRequestDevice {
	return v.value
}

func (v *NullableBriefCoolingIntakeRequestDevice) Set(val *BriefCoolingIntakeRequestDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefCoolingIntakeRequestDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefCoolingIntakeRequestDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefCoolingIntakeRequestDevice(val *BriefCoolingIntakeRequestDevice) *NullableBriefCoolingIntakeRequestDevice {
	return &NullableBriefCoolingIntakeRequestDevice{value: val, isSet: true}
}

func (v NullableBriefCoolingIntakeRequestDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefCoolingIntakeRequestDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
