/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkWirelessLANRequestAuthType * `open` - Open * `wep` - WEP * `wpa-personal` - WPA Personal (PSK) * `wpa-enterprise` - WPA Enterprise
type BulkWirelessLANRequestAuthType string

// List of BulkWirelessLANRequest_auth_type
const (
	BULKWIRELESSLANREQUESTAUTHTYPE_OPEN           BulkWirelessLANRequestAuthType = "open"
	BULKWIRELESSLANREQUESTAUTHTYPE_WEP            BulkWirelessLANRequestAuthType = "wep"
	BULKWIRELESSLANREQUESTAUTHTYPE_WPA_PERSONAL   BulkWirelessLANRequestAuthType = "wpa-personal"
	BULKWIRELESSLANREQUESTAUTHTYPE_WPA_ENTERPRISE BulkWirelessLANRequestAuthType = "wpa-enterprise"
	BULKWIRELESSLANREQUESTAUTHTYPE_EMPTY          BulkWirelessLANRequestAuthType = ""
)

// All allowed values of BulkWirelessLANRequestAuthType enum
var AllowedBulkWirelessLANRequestAuthTypeEnumValues = []BulkWirelessLANRequestAuthType{
	"open",
	"wep",
	"wpa-personal",
	"wpa-enterprise",
	"",
}

func (v *BulkWirelessLANRequestAuthType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkWirelessLANRequestAuthType(value)
	for _, existing := range AllowedBulkWirelessLANRequestAuthTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkWirelessLANRequestAuthType", value)
}

// NewBulkWirelessLANRequestAuthTypeFromValue returns a pointer to a valid BulkWirelessLANRequestAuthType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkWirelessLANRequestAuthTypeFromValue(v string) (*BulkWirelessLANRequestAuthType, error) {
	ev := BulkWirelessLANRequestAuthType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkWirelessLANRequestAuthType: valid values are %v", v, AllowedBulkWirelessLANRequestAuthTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkWirelessLANRequestAuthType) IsValid() bool {
	for _, existing := range AllowedBulkWirelessLANRequestAuthTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkWirelessLANRequest_auth_type value
func (v BulkWirelessLANRequestAuthType) Ptr() *BulkWirelessLANRequestAuthType {
	return &v
}

type NullableBulkWirelessLANRequestAuthType struct {
	value *BulkWirelessLANRequestAuthType
	isSet bool
}

func (v NullableBulkWirelessLANRequestAuthType) Get() *BulkWirelessLANRequestAuthType {
	return v.value
}

func (v *NullableBulkWirelessLANRequestAuthType) Set(val *BulkWirelessLANRequestAuthType) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWirelessLANRequestAuthType) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWirelessLANRequestAuthType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWirelessLANRequestAuthType(val *BulkWirelessLANRequestAuthType) *NullableBulkWirelessLANRequestAuthType {
	return &NullableBulkWirelessLANRequestAuthType{value: val, isSet: true}
}

func (v NullableBulkWirelessLANRequestAuthType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWirelessLANRequestAuthType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
