/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkCoolingIntakeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkCoolingIntakeRequest{}

// PatchedBulkCoolingIntakeRequest Adds an `owner` field for models which have a ForeignKey to users.Owner.
type PatchedBulkCoolingIntakeRequest struct {
	Id     int32                                `json:"id"`
	Device *BriefCoolingIntakeRequestDevice     `json:"device,omitempty"`
	Module NullableBulkConsolePortRequestModule `json:"module,omitempty"`
	Name   *string                              `json:"name,omitempty"`
	// Physical label
	Label                *string                                      `json:"label,omitempty"`
	Type                 NullableBulkCoolingIntakeRequestType         `json:"type,omitempty"`
	Diameter             NullableFloat64                              `json:"diameter,omitempty"`
	DiameterUnit         NullableBulkCoolingIntakeRequestDiameterUnit `json:"diameter_unit,omitempty"`
	MaxFlow              NullableFloat64                              `json:"max_flow,omitempty"`
	MaxFlowUnit          NullableBulkCoolingFeedRequestMaxFlowUnit    `json:"max_flow_unit,omitempty"`
	CoolingOutflow       NullableNestedCoolingOutflowRequest          `json:"cooling_outflow,omitempty"`
	Description          *string                                      `json:"description,omitempty"`
	Owner                NullableASNRangeRequestOwner                 `json:"owner,omitempty"`
	Tags                 []NestedTagRequest                           `json:"tags,omitempty"`
	CustomFields         map[string]interface{}                       `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkCoolingIntakeRequest PatchedBulkCoolingIntakeRequest

// NewPatchedBulkCoolingIntakeRequest instantiates a new PatchedBulkCoolingIntakeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkCoolingIntakeRequest(id int32) *PatchedBulkCoolingIntakeRequest {
	this := PatchedBulkCoolingIntakeRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkCoolingIntakeRequestWithDefaults instantiates a new PatchedBulkCoolingIntakeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkCoolingIntakeRequestWithDefaults() *PatchedBulkCoolingIntakeRequest {
	this := PatchedBulkCoolingIntakeRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkCoolingIntakeRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkCoolingIntakeRequest) SetId(v int32) {
	o.Id = v
}

// GetDevice returns the Device field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetDevice() BriefCoolingIntakeRequestDevice {
	if o == nil || IsNil(o.Device) {
		var ret BriefCoolingIntakeRequestDevice
		return ret
	}
	return *o.Device
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetDeviceOk() (*BriefCoolingIntakeRequestDevice, bool) {
	if o == nil || IsNil(o.Device) {
		return nil, false
	}
	return o.Device, true
}

// HasDevice returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasDevice() bool {
	if o != nil && !IsNil(o.Device) {
		return true
	}

	return false
}

// SetDevice gets a reference to the given BriefCoolingIntakeRequestDevice and assigns it to the Device field.
func (o *PatchedBulkCoolingIntakeRequest) SetDevice(v BriefCoolingIntakeRequestDevice) {
	o.Device = &v
}

// GetModule returns the Module field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetModule() BulkConsolePortRequestModule {
	if o == nil || IsNil(o.Module.Get()) {
		var ret BulkConsolePortRequestModule
		return ret
	}
	return *o.Module.Get()
}

// GetModuleOk returns a tuple with the Module field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetModuleOk() (*BulkConsolePortRequestModule, bool) {
	if o == nil {
		return nil, false
	}
	return o.Module.Get(), o.Module.IsSet()
}

// HasModule returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasModule() bool {
	if o != nil && o.Module.IsSet() {
		return true
	}

	return false
}

// SetModule gets a reference to the given NullableBulkConsolePortRequestModule and assigns it to the Module field.
func (o *PatchedBulkCoolingIntakeRequest) SetModule(v BulkConsolePortRequestModule) {
	o.Module.Set(&v)
}

// SetModuleNil sets the value for Module to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetModuleNil() {
	o.Module.Set(nil)
}

// UnsetModule ensures that no value is present for Module, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetModule() {
	o.Module.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedBulkCoolingIntakeRequest) SetName(v string) {
	o.Name = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *PatchedBulkCoolingIntakeRequest) SetLabel(v string) {
	o.Label = &v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetType() BulkCoolingIntakeRequestType {
	if o == nil || IsNil(o.Type.Get()) {
		var ret BulkCoolingIntakeRequestType
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetTypeOk() (*BulkCoolingIntakeRequestType, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableBulkCoolingIntakeRequestType and assigns it to the Type field.
func (o *PatchedBulkCoolingIntakeRequest) SetType(v BulkCoolingIntakeRequestType) {
	o.Type.Set(&v)
}

// SetTypeNil sets the value for Type to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetType() {
	o.Type.Unset()
}

// GetDiameter returns the Diameter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetDiameter() float64 {
	if o == nil || IsNil(o.Diameter.Get()) {
		var ret float64
		return ret
	}
	return *o.Diameter.Get()
}

// GetDiameterOk returns a tuple with the Diameter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetDiameterOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Diameter.Get(), o.Diameter.IsSet()
}

// HasDiameter returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasDiameter() bool {
	if o != nil && o.Diameter.IsSet() {
		return true
	}

	return false
}

// SetDiameter gets a reference to the given NullableFloat64 and assigns it to the Diameter field.
func (o *PatchedBulkCoolingIntakeRequest) SetDiameter(v float64) {
	o.Diameter.Set(&v)
}

// SetDiameterNil sets the value for Diameter to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetDiameterNil() {
	o.Diameter.Set(nil)
}

// UnsetDiameter ensures that no value is present for Diameter, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetDiameter() {
	o.Diameter.Unset()
}

// GetDiameterUnit returns the DiameterUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetDiameterUnit() BulkCoolingIntakeRequestDiameterUnit {
	if o == nil || IsNil(o.DiameterUnit.Get()) {
		var ret BulkCoolingIntakeRequestDiameterUnit
		return ret
	}
	return *o.DiameterUnit.Get()
}

// GetDiameterUnitOk returns a tuple with the DiameterUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetDiameterUnitOk() (*BulkCoolingIntakeRequestDiameterUnit, bool) {
	if o == nil {
		return nil, false
	}
	return o.DiameterUnit.Get(), o.DiameterUnit.IsSet()
}

// HasDiameterUnit returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasDiameterUnit() bool {
	if o != nil && o.DiameterUnit.IsSet() {
		return true
	}

	return false
}

// SetDiameterUnit gets a reference to the given NullableBulkCoolingIntakeRequestDiameterUnit and assigns it to the DiameterUnit field.
func (o *PatchedBulkCoolingIntakeRequest) SetDiameterUnit(v BulkCoolingIntakeRequestDiameterUnit) {
	o.DiameterUnit.Set(&v)
}

// SetDiameterUnitNil sets the value for DiameterUnit to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetDiameterUnitNil() {
	o.DiameterUnit.Set(nil)
}

// UnsetDiameterUnit ensures that no value is present for DiameterUnit, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetDiameterUnit() {
	o.DiameterUnit.Unset()
}

// GetMaxFlow returns the MaxFlow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetMaxFlow() float64 {
	if o == nil || IsNil(o.MaxFlow.Get()) {
		var ret float64
		return ret
	}
	return *o.MaxFlow.Get()
}

// GetMaxFlowOk returns a tuple with the MaxFlow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetMaxFlowOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxFlow.Get(), o.MaxFlow.IsSet()
}

// HasMaxFlow returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasMaxFlow() bool {
	if o != nil && o.MaxFlow.IsSet() {
		return true
	}

	return false
}

// SetMaxFlow gets a reference to the given NullableFloat64 and assigns it to the MaxFlow field.
func (o *PatchedBulkCoolingIntakeRequest) SetMaxFlow(v float64) {
	o.MaxFlow.Set(&v)
}

// SetMaxFlowNil sets the value for MaxFlow to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetMaxFlowNil() {
	o.MaxFlow.Set(nil)
}

// UnsetMaxFlow ensures that no value is present for MaxFlow, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetMaxFlow() {
	o.MaxFlow.Unset()
}

// GetMaxFlowUnit returns the MaxFlowUnit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetMaxFlowUnit() BulkCoolingFeedRequestMaxFlowUnit {
	if o == nil || IsNil(o.MaxFlowUnit.Get()) {
		var ret BulkCoolingFeedRequestMaxFlowUnit
		return ret
	}
	return *o.MaxFlowUnit.Get()
}

// GetMaxFlowUnitOk returns a tuple with the MaxFlowUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetMaxFlowUnitOk() (*BulkCoolingFeedRequestMaxFlowUnit, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxFlowUnit.Get(), o.MaxFlowUnit.IsSet()
}

// HasMaxFlowUnit returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasMaxFlowUnit() bool {
	if o != nil && o.MaxFlowUnit.IsSet() {
		return true
	}

	return false
}

// SetMaxFlowUnit gets a reference to the given NullableBulkCoolingFeedRequestMaxFlowUnit and assigns it to the MaxFlowUnit field.
func (o *PatchedBulkCoolingIntakeRequest) SetMaxFlowUnit(v BulkCoolingFeedRequestMaxFlowUnit) {
	o.MaxFlowUnit.Set(&v)
}

// SetMaxFlowUnitNil sets the value for MaxFlowUnit to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetMaxFlowUnitNil() {
	o.MaxFlowUnit.Set(nil)
}

// UnsetMaxFlowUnit ensures that no value is present for MaxFlowUnit, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetMaxFlowUnit() {
	o.MaxFlowUnit.Unset()
}

// GetCoolingOutflow returns the CoolingOutflow field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetCoolingOutflow() NestedCoolingOutflowRequest {
	if o == nil || IsNil(o.CoolingOutflow.Get()) {
		var ret NestedCoolingOutflowRequest
		return ret
	}
	return *o.CoolingOutflow.Get()
}

// GetCoolingOutflowOk returns a tuple with the CoolingOutflow field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetCoolingOutflowOk() (*NestedCoolingOutflowRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.CoolingOutflow.Get(), o.CoolingOutflow.IsSet()
}

// HasCoolingOutflow returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasCoolingOutflow() bool {
	if o != nil && o.CoolingOutflow.IsSet() {
		return true
	}

	return false
}

// SetCoolingOutflow gets a reference to the given NullableNestedCoolingOutflowRequest and assigns it to the CoolingOutflow field.
func (o *PatchedBulkCoolingIntakeRequest) SetCoolingOutflow(v NestedCoolingOutflowRequest) {
	o.CoolingOutflow.Set(&v)
}

// SetCoolingOutflowNil sets the value for CoolingOutflow to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetCoolingOutflowNil() {
	o.CoolingOutflow.Set(nil)
}

// UnsetCoolingOutflow ensures that no value is present for CoolingOutflow, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetCoolingOutflow() {
	o.CoolingOutflow.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedBulkCoolingIntakeRequest) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkCoolingIntakeRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkCoolingIntakeRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *PatchedBulkCoolingIntakeRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *PatchedBulkCoolingIntakeRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedBulkCoolingIntakeRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedBulkCoolingIntakeRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkCoolingIntakeRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedBulkCoolingIntakeRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedBulkCoolingIntakeRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o PatchedBulkCoolingIntakeRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkCoolingIntakeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Device) {
		toSerialize["device"] = o.Device
	}
	if o.Module.IsSet() {
		toSerialize["module"] = o.Module.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.Diameter.IsSet() {
		toSerialize["diameter"] = o.Diameter.Get()
	}
	if o.DiameterUnit.IsSet() {
		toSerialize["diameter_unit"] = o.DiameterUnit.Get()
	}
	if o.MaxFlow.IsSet() {
		toSerialize["max_flow"] = o.MaxFlow.Get()
	}
	if o.MaxFlowUnit.IsSet() {
		toSerialize["max_flow_unit"] = o.MaxFlowUnit.Get()
	}
	if o.CoolingOutflow.IsSet() {
		toSerialize["cooling_outflow"] = o.CoolingOutflow.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkCoolingIntakeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkCoolingIntakeRequest := _PatchedBulkCoolingIntakeRequest{}

	err = json.Unmarshal(data, &varPatchedBulkCoolingIntakeRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkCoolingIntakeRequest(varPatchedBulkCoolingIntakeRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "device")
		delete(additionalProperties, "module")
		delete(additionalProperties, "name")
		delete(additionalProperties, "label")
		delete(additionalProperties, "type")
		delete(additionalProperties, "diameter")
		delete(additionalProperties, "diameter_unit")
		delete(additionalProperties, "max_flow")
		delete(additionalProperties, "max_flow_unit")
		delete(additionalProperties, "cooling_outflow")
		delete(additionalProperties, "description")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkCoolingIntakeRequest struct {
	value *PatchedBulkCoolingIntakeRequest
	isSet bool
}

func (v NullablePatchedBulkCoolingIntakeRequest) Get() *PatchedBulkCoolingIntakeRequest {
	return v.value
}

func (v *NullablePatchedBulkCoolingIntakeRequest) Set(val *PatchedBulkCoolingIntakeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkCoolingIntakeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkCoolingIntakeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkCoolingIntakeRequest(val *PatchedBulkCoolingIntakeRequest) *NullablePatchedBulkCoolingIntakeRequest {
	return &NullablePatchedBulkCoolingIntakeRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkCoolingIntakeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkCoolingIntakeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
