/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkInterfaceRequestPoeMode * `pd` - PD * `pse` - PSE
type BulkInterfaceRequestPoeMode string

// List of BulkInterfaceRequest_poe_mode
const (
	BULKINTERFACEREQUESTPOEMODE_PD    BulkInterfaceRequestPoeMode = "pd"
	BULKINTERFACEREQUESTPOEMODE_PSE   BulkInterfaceRequestPoeMode = "pse"
	BULKINTERFACEREQUESTPOEMODE_EMPTY BulkInterfaceRequestPoeMode = ""
)

// All allowed values of BulkInterfaceRequestPoeMode enum
var AllowedBulkInterfaceRequestPoeModeEnumValues = []BulkInterfaceRequestPoeMode{
	"pd",
	"pse",
	"",
}

func (v *BulkInterfaceRequestPoeMode) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkInterfaceRequestPoeMode(value)
	for _, existing := range AllowedBulkInterfaceRequestPoeModeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkInterfaceRequestPoeMode", value)
}

// NewBulkInterfaceRequestPoeModeFromValue returns a pointer to a valid BulkInterfaceRequestPoeMode
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkInterfaceRequestPoeModeFromValue(v string) (*BulkInterfaceRequestPoeMode, error) {
	ev := BulkInterfaceRequestPoeMode(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkInterfaceRequestPoeMode: valid values are %v", v, AllowedBulkInterfaceRequestPoeModeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkInterfaceRequestPoeMode) IsValid() bool {
	for _, existing := range AllowedBulkInterfaceRequestPoeModeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkInterfaceRequest_poe_mode value
func (v BulkInterfaceRequestPoeMode) Ptr() *BulkInterfaceRequestPoeMode {
	return &v
}

type NullableBulkInterfaceRequestPoeMode struct {
	value *BulkInterfaceRequestPoeMode
	isSet bool
}

func (v NullableBulkInterfaceRequestPoeMode) Get() *BulkInterfaceRequestPoeMode {
	return v.value
}

func (v *NullableBulkInterfaceRequestPoeMode) Set(val *BulkInterfaceRequestPoeMode) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkInterfaceRequestPoeMode) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkInterfaceRequestPoeMode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkInterfaceRequestPoeMode(val *BulkInterfaceRequestPoeMode) *NullableBulkInterfaceRequestPoeMode {
	return &NullableBulkInterfaceRequestPoeMode{value: val, isSet: true}
}

func (v NullableBulkInterfaceRequestPoeMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkInterfaceRequestPoeMode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
