/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkCustomFieldRequestFilterLogic * `disabled` - Disabled * `loose` - Loose * `exact` - Exact
type BulkCustomFieldRequestFilterLogic string

// List of BulkCustomFieldRequest_filter_logic
const (
	BULKCUSTOMFIELDREQUESTFILTERLOGIC_DISABLED BulkCustomFieldRequestFilterLogic = "disabled"
	BULKCUSTOMFIELDREQUESTFILTERLOGIC_LOOSE    BulkCustomFieldRequestFilterLogic = "loose"
	BULKCUSTOMFIELDREQUESTFILTERLOGIC_EXACT    BulkCustomFieldRequestFilterLogic = "exact"
)

// All allowed values of BulkCustomFieldRequestFilterLogic enum
var AllowedBulkCustomFieldRequestFilterLogicEnumValues = []BulkCustomFieldRequestFilterLogic{
	"disabled",
	"loose",
	"exact",
}

func (v *BulkCustomFieldRequestFilterLogic) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkCustomFieldRequestFilterLogic(value)
	for _, existing := range AllowedBulkCustomFieldRequestFilterLogicEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkCustomFieldRequestFilterLogic", value)
}

// NewBulkCustomFieldRequestFilterLogicFromValue returns a pointer to a valid BulkCustomFieldRequestFilterLogic
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkCustomFieldRequestFilterLogicFromValue(v string) (*BulkCustomFieldRequestFilterLogic, error) {
	ev := BulkCustomFieldRequestFilterLogic(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkCustomFieldRequestFilterLogic: valid values are %v", v, AllowedBulkCustomFieldRequestFilterLogicEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkCustomFieldRequestFilterLogic) IsValid() bool {
	for _, existing := range AllowedBulkCustomFieldRequestFilterLogicEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkCustomFieldRequest_filter_logic value
func (v BulkCustomFieldRequestFilterLogic) Ptr() *BulkCustomFieldRequestFilterLogic {
	return &v
}

type NullableBulkCustomFieldRequestFilterLogic struct {
	value *BulkCustomFieldRequestFilterLogic
	isSet bool
}

func (v NullableBulkCustomFieldRequestFilterLogic) Get() *BulkCustomFieldRequestFilterLogic {
	return v.value
}

func (v *NullableBulkCustomFieldRequestFilterLogic) Set(val *BulkCustomFieldRequestFilterLogic) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCustomFieldRequestFilterLogic) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCustomFieldRequestFilterLogic) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCustomFieldRequestFilterLogic(val *BulkCustomFieldRequestFilterLogic) *NullableBulkCustomFieldRequestFilterLogic {
	return &NullableBulkCustomFieldRequestFilterLogic{value: val, isSet: true}
}

func (v NullableBulkCustomFieldRequestFilterLogic) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCustomFieldRequestFilterLogic) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
