/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkSiteRequestGroup - struct for BulkSiteRequestGroup
type BulkSiteRequestGroup struct {
	BriefSiteGroupRequest *BriefSiteGroupRequest
	Int32                 *int32
}

// BriefSiteGroupRequestAsBulkSiteRequestGroup is a convenience function that returns BriefSiteGroupRequest wrapped in BulkSiteRequestGroup
func BriefSiteGroupRequestAsBulkSiteRequestGroup(v *BriefSiteGroupRequest) BulkSiteRequestGroup {
	return BulkSiteRequestGroup{
		BriefSiteGroupRequest: v,
	}
}

// int32AsBulkSiteRequestGroup is a convenience function that returns int32 wrapped in BulkSiteRequestGroup
func Int32AsBulkSiteRequestGroup(v *int32) BulkSiteRequestGroup {
	return BulkSiteRequestGroup{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkSiteRequestGroup) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefSiteGroupRequest
	err = newStrictDecoder(data).Decode(&dst.BriefSiteGroupRequest)
	if err == nil {
		jsonBriefSiteGroupRequest, _ := json.Marshal(dst.BriefSiteGroupRequest)
		if string(jsonBriefSiteGroupRequest) == "{}" { // empty struct
			dst.BriefSiteGroupRequest = nil
		} else {
			if err = validator.Validate(dst.BriefSiteGroupRequest); err != nil {
				dst.BriefSiteGroupRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefSiteGroupRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefSiteGroupRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkSiteRequestGroup)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkSiteRequestGroup): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(BulkSiteRequestGroup)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkSiteRequestGroup) MarshalJSON() ([]byte, error) {
	if src.BriefSiteGroupRequest != nil {
		return json.Marshal(&src.BriefSiteGroupRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkSiteRequestGroup) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefSiteGroupRequest != nil {
		return obj.BriefSiteGroupRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkSiteRequestGroup) GetActualInstanceValue() interface{} {
	if obj.BriefSiteGroupRequest != nil {
		return *obj.BriefSiteGroupRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkSiteRequestGroup struct {
	value *BulkSiteRequestGroup
	isSet bool
}

func (v NullableBulkSiteRequestGroup) Get() *BulkSiteRequestGroup {
	return v.value
}

func (v *NullableBulkSiteRequestGroup) Set(val *BulkSiteRequestGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSiteRequestGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSiteRequestGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSiteRequestGroup(val *BulkSiteRequestGroup) *NullableBulkSiteRequestGroup {
	return &NullableBulkSiteRequestGroup{value: val, isSet: true}
}

func (v NullableBulkSiteRequestGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSiteRequestGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
