/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// CoolingSourceFluidTypeLabel the model 'CoolingSourceFluidTypeLabel'
type CoolingSourceFluidTypeLabel string

// List of CoolingSource_fluid_type_label
const (
	COOLINGSOURCEFLUIDTYPELABEL_WATER        CoolingSourceFluidTypeLabel = "Water"
	COOLINGSOURCEFLUIDTYPELABEL_WATER_GLYCOL CoolingSourceFluidTypeLabel = "Water/glycol"
	COOLINGSOURCEFLUIDTYPELABEL_DIELECTRIC   CoolingSourceFluidTypeLabel = "Dielectric"
	COOLINGSOURCEFLUIDTYPELABEL_REFRIGERANT  CoolingSourceFluidTypeLabel = "Refrigerant"
)

// All allowed values of CoolingSourceFluidTypeLabel enum
var AllowedCoolingSourceFluidTypeLabelEnumValues = []CoolingSourceFluidTypeLabel{
	"Water",
	"Water/glycol",
	"Dielectric",
	"Refrigerant",
}

func (v *CoolingSourceFluidTypeLabel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := CoolingSourceFluidTypeLabel(value)
	for _, existing := range AllowedCoolingSourceFluidTypeLabelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid CoolingSourceFluidTypeLabel", value)
}

// NewCoolingSourceFluidTypeLabelFromValue returns a pointer to a valid CoolingSourceFluidTypeLabel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewCoolingSourceFluidTypeLabelFromValue(v string) (*CoolingSourceFluidTypeLabel, error) {
	ev := CoolingSourceFluidTypeLabel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for CoolingSourceFluidTypeLabel: valid values are %v", v, AllowedCoolingSourceFluidTypeLabelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v CoolingSourceFluidTypeLabel) IsValid() bool {
	for _, existing := range AllowedCoolingSourceFluidTypeLabelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to CoolingSource_fluid_type_label value
func (v CoolingSourceFluidTypeLabel) Ptr() *CoolingSourceFluidTypeLabel {
	return &v
}

type NullableCoolingSourceFluidTypeLabel struct {
	value *CoolingSourceFluidTypeLabel
	isSet bool
}

func (v NullableCoolingSourceFluidTypeLabel) Get() *CoolingSourceFluidTypeLabel {
	return v.value
}

func (v *NullableCoolingSourceFluidTypeLabel) Set(val *CoolingSourceFluidTypeLabel) {
	v.value = val
	v.isSet = true
}

func (v NullableCoolingSourceFluidTypeLabel) IsSet() bool {
	return v.isSet
}

func (v *NullableCoolingSourceFluidTypeLabel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoolingSourceFluidTypeLabel(val *CoolingSourceFluidTypeLabel) *NullableCoolingSourceFluidTypeLabel {
	return &NullableCoolingSourceFluidTypeLabel{value: val, isSet: true}
}

func (v NullableCoolingSourceFluidTypeLabel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoolingSourceFluidTypeLabel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
