/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// BulkVLANRequestSite - struct for BulkVLANRequestSite
type BulkVLANRequestSite struct {
	BriefSiteRequest *BriefSiteRequest
	Int32            *int32
}

// BriefSiteRequestAsBulkVLANRequestSite is a convenience function that returns BriefSiteRequest wrapped in BulkVLANRequestSite
func BriefSiteRequestAsBulkVLANRequestSite(v *BriefSiteRequest) BulkVLANRequestSite {
	return BulkVLANRequestSite{
		BriefSiteRequest: v,
	}
}

// int32AsBulkVLANRequestSite is a convenience function that returns int32 wrapped in BulkVLANRequestSite
func Int32AsBulkVLANRequestSite(v *int32) BulkVLANRequestSite {
	return BulkVLANRequestSite{
		Int32: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *BulkVLANRequestSite) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into BriefSiteRequest
	err = newStrictDecoder(data).Decode(&dst.BriefSiteRequest)
	if err == nil {
		jsonBriefSiteRequest, _ := json.Marshal(dst.BriefSiteRequest)
		if string(jsonBriefSiteRequest) == "{}" { // empty struct
			dst.BriefSiteRequest = nil
		} else {
			if err = validator.Validate(dst.BriefSiteRequest); err != nil {
				dst.BriefSiteRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.BriefSiteRequest = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BriefSiteRequest = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BulkVLANRequestSite)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(BulkVLANRequestSite): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(BulkVLANRequestSite)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BulkVLANRequestSite) MarshalJSON() ([]byte, error) {
	if src.BriefSiteRequest != nil {
		return json.Marshal(&src.BriefSiteRequest)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BulkVLANRequestSite) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.BriefSiteRequest != nil {
		return obj.BriefSiteRequest
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj BulkVLANRequestSite) GetActualInstanceValue() interface{} {
	if obj.BriefSiteRequest != nil {
		return *obj.BriefSiteRequest
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableBulkVLANRequestSite struct {
	value *BulkVLANRequestSite
	isSet bool
}

func (v NullableBulkVLANRequestSite) Get() *BulkVLANRequestSite {
	return v.value
}

func (v *NullableBulkVLANRequestSite) Set(val *BulkVLANRequestSite) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkVLANRequestSite) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkVLANRequestSite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkVLANRequestSite(val *BulkVLANRequestSite) *NullableBulkVLANRequestSite {
	return &NullableBulkVLANRequestSite{value: val, isSet: true}
}

func (v NullableBulkVLANRequestSite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkVLANRequestSite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
