/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkTunnelRequestStatus * `planned` - Planned * `active` - Active * `disabled` - Disabled
type BulkTunnelRequestStatus string

// List of BulkTunnelRequest_status
const (
	BULKTUNNELREQUESTSTATUS_PLANNED  BulkTunnelRequestStatus = "planned"
	BULKTUNNELREQUESTSTATUS_ACTIVE   BulkTunnelRequestStatus = "active"
	BULKTUNNELREQUESTSTATUS_DISABLED BulkTunnelRequestStatus = "disabled"
)

// All allowed values of BulkTunnelRequestStatus enum
var AllowedBulkTunnelRequestStatusEnumValues = []BulkTunnelRequestStatus{
	"planned",
	"active",
	"disabled",
}

func (v *BulkTunnelRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkTunnelRequestStatus(value)
	for _, existing := range AllowedBulkTunnelRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkTunnelRequestStatus", value)
}

// NewBulkTunnelRequestStatusFromValue returns a pointer to a valid BulkTunnelRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkTunnelRequestStatusFromValue(v string) (*BulkTunnelRequestStatus, error) {
	ev := BulkTunnelRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkTunnelRequestStatus: valid values are %v", v, AllowedBulkTunnelRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkTunnelRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkTunnelRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkTunnelRequest_status value
func (v BulkTunnelRequestStatus) Ptr() *BulkTunnelRequestStatus {
	return &v
}

type NullableBulkTunnelRequestStatus struct {
	value *BulkTunnelRequestStatus
	isSet bool
}

func (v NullableBulkTunnelRequestStatus) Get() *BulkTunnelRequestStatus {
	return v.value
}

func (v *NullableBulkTunnelRequestStatus) Set(val *BulkTunnelRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkTunnelRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkTunnelRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkTunnelRequestStatus(val *BulkTunnelRequestStatus) *NullableBulkTunnelRequestStatus {
	return &NullableBulkTunnelRequestStatus{value: val, isSet: true}
}

func (v NullableBulkTunnelRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkTunnelRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
