/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkConsolePortRequestType * `de-9` - DE-9 * `db-25` - DB-25 * `rj-11` - RJ-11 * `rj-12` - RJ-12 * `rj-45` - RJ-45 * `mini-din-8` - Mini-DIN 8 * `usb-a` - USB Type A * `usb-b` - USB Type B * `usb-c` - USB Type C * `usb-mini-a` - USB Mini A * `usb-mini-b` - USB Mini B * `usb-micro-a` - USB Micro A * `usb-micro-b` - USB Micro B * `usb-micro-ab` - USB Micro AB * `other` - Other
type BulkConsolePortRequestType string

// List of BulkConsolePortRequest_type
const (
	BULKCONSOLEPORTREQUESTTYPE_DE_9         BulkConsolePortRequestType = "de-9"
	BULKCONSOLEPORTREQUESTTYPE_DB_25        BulkConsolePortRequestType = "db-25"
	BULKCONSOLEPORTREQUESTTYPE_RJ_11        BulkConsolePortRequestType = "rj-11"
	BULKCONSOLEPORTREQUESTTYPE_RJ_12        BulkConsolePortRequestType = "rj-12"
	BULKCONSOLEPORTREQUESTTYPE_RJ_45        BulkConsolePortRequestType = "rj-45"
	BULKCONSOLEPORTREQUESTTYPE_MINI_DIN_8   BulkConsolePortRequestType = "mini-din-8"
	BULKCONSOLEPORTREQUESTTYPE_USB_A        BulkConsolePortRequestType = "usb-a"
	BULKCONSOLEPORTREQUESTTYPE_USB_B        BulkConsolePortRequestType = "usb-b"
	BULKCONSOLEPORTREQUESTTYPE_USB_C        BulkConsolePortRequestType = "usb-c"
	BULKCONSOLEPORTREQUESTTYPE_USB_MINI_A   BulkConsolePortRequestType = "usb-mini-a"
	BULKCONSOLEPORTREQUESTTYPE_USB_MINI_B   BulkConsolePortRequestType = "usb-mini-b"
	BULKCONSOLEPORTREQUESTTYPE_USB_MICRO_A  BulkConsolePortRequestType = "usb-micro-a"
	BULKCONSOLEPORTREQUESTTYPE_USB_MICRO_B  BulkConsolePortRequestType = "usb-micro-b"
	BULKCONSOLEPORTREQUESTTYPE_USB_MICRO_AB BulkConsolePortRequestType = "usb-micro-ab"
	BULKCONSOLEPORTREQUESTTYPE_OTHER        BulkConsolePortRequestType = "other"
	BULKCONSOLEPORTREQUESTTYPE_EMPTY        BulkConsolePortRequestType = ""
)

// All allowed values of BulkConsolePortRequestType enum
var AllowedBulkConsolePortRequestTypeEnumValues = []BulkConsolePortRequestType{
	"de-9",
	"db-25",
	"rj-11",
	"rj-12",
	"rj-45",
	"mini-din-8",
	"usb-a",
	"usb-b",
	"usb-c",
	"usb-mini-a",
	"usb-mini-b",
	"usb-micro-a",
	"usb-micro-b",
	"usb-micro-ab",
	"other",
	"",
}

func (v *BulkConsolePortRequestType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkConsolePortRequestType(value)
	for _, existing := range AllowedBulkConsolePortRequestTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkConsolePortRequestType", value)
}

// NewBulkConsolePortRequestTypeFromValue returns a pointer to a valid BulkConsolePortRequestType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkConsolePortRequestTypeFromValue(v string) (*BulkConsolePortRequestType, error) {
	ev := BulkConsolePortRequestType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkConsolePortRequestType: valid values are %v", v, AllowedBulkConsolePortRequestTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkConsolePortRequestType) IsValid() bool {
	for _, existing := range AllowedBulkConsolePortRequestTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkConsolePortRequest_type value
func (v BulkConsolePortRequestType) Ptr() *BulkConsolePortRequestType {
	return &v
}

type NullableBulkConsolePortRequestType struct {
	value *BulkConsolePortRequestType
	isSet bool
}

func (v NullableBulkConsolePortRequestType) Get() *BulkConsolePortRequestType {
	return v.value
}

func (v *NullableBulkConsolePortRequestType) Set(val *BulkConsolePortRequestType) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkConsolePortRequestType) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkConsolePortRequestType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkConsolePortRequestType(val *BulkConsolePortRequestType) *NullableBulkConsolePortRequestType {
	return &NullableBulkConsolePortRequestType{value: val, isSet: true}
}

func (v NullableBulkConsolePortRequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkConsolePortRequestType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
