/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkJournalEntryRequestKind * `info` - Info * `success` - Success * `warning` - Warning * `danger` - Danger
type BulkJournalEntryRequestKind string

// List of BulkJournalEntryRequest_kind
const (
	BULKJOURNALENTRYREQUESTKIND_INFO    BulkJournalEntryRequestKind = "info"
	BULKJOURNALENTRYREQUESTKIND_SUCCESS BulkJournalEntryRequestKind = "success"
	BULKJOURNALENTRYREQUESTKIND_WARNING BulkJournalEntryRequestKind = "warning"
	BULKJOURNALENTRYREQUESTKIND_DANGER  BulkJournalEntryRequestKind = "danger"
)

// All allowed values of BulkJournalEntryRequestKind enum
var AllowedBulkJournalEntryRequestKindEnumValues = []BulkJournalEntryRequestKind{
	"info",
	"success",
	"warning",
	"danger",
}

func (v *BulkJournalEntryRequestKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkJournalEntryRequestKind(value)
	for _, existing := range AllowedBulkJournalEntryRequestKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkJournalEntryRequestKind", value)
}

// NewBulkJournalEntryRequestKindFromValue returns a pointer to a valid BulkJournalEntryRequestKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkJournalEntryRequestKindFromValue(v string) (*BulkJournalEntryRequestKind, error) {
	ev := BulkJournalEntryRequestKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkJournalEntryRequestKind: valid values are %v", v, AllowedBulkJournalEntryRequestKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkJournalEntryRequestKind) IsValid() bool {
	for _, existing := range AllowedBulkJournalEntryRequestKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkJournalEntryRequest_kind value
func (v BulkJournalEntryRequestKind) Ptr() *BulkJournalEntryRequestKind {
	return &v
}

type NullableBulkJournalEntryRequestKind struct {
	value *BulkJournalEntryRequestKind
	isSet bool
}

func (v NullableBulkJournalEntryRequestKind) Get() *BulkJournalEntryRequestKind {
	return v.value
}

func (v *NullableBulkJournalEntryRequestKind) Set(val *BulkJournalEntryRequestKind) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkJournalEntryRequestKind) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkJournalEntryRequestKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkJournalEntryRequestKind(val *BulkJournalEntryRequestKind) *NullableBulkJournalEntryRequestKind {
	return &NullableBulkJournalEntryRequestKind{value: val, isSet: true}
}

func (v NullableBulkJournalEntryRequestKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkJournalEntryRequestKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
