/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkIPAddressRequestStatus * `active` - Active * `reserved` - Reserved * `deprecated` - Deprecated * `dhcp` - DHCP * `slaac` - SLAAC
type BulkIPAddressRequestStatus string

// List of BulkIPAddressRequest_status
const (
	BULKIPADDRESSREQUESTSTATUS_ACTIVE     BulkIPAddressRequestStatus = "active"
	BULKIPADDRESSREQUESTSTATUS_RESERVED   BulkIPAddressRequestStatus = "reserved"
	BULKIPADDRESSREQUESTSTATUS_DEPRECATED BulkIPAddressRequestStatus = "deprecated"
	BULKIPADDRESSREQUESTSTATUS_DHCP       BulkIPAddressRequestStatus = "dhcp"
	BULKIPADDRESSREQUESTSTATUS_SLAAC      BulkIPAddressRequestStatus = "slaac"
)

// All allowed values of BulkIPAddressRequestStatus enum
var AllowedBulkIPAddressRequestStatusEnumValues = []BulkIPAddressRequestStatus{
	"active",
	"reserved",
	"deprecated",
	"dhcp",
	"slaac",
}

func (v *BulkIPAddressRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkIPAddressRequestStatus(value)
	for _, existing := range AllowedBulkIPAddressRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkIPAddressRequestStatus", value)
}

// NewBulkIPAddressRequestStatusFromValue returns a pointer to a valid BulkIPAddressRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkIPAddressRequestStatusFromValue(v string) (*BulkIPAddressRequestStatus, error) {
	ev := BulkIPAddressRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkIPAddressRequestStatus: valid values are %v", v, AllowedBulkIPAddressRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkIPAddressRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkIPAddressRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkIPAddressRequest_status value
func (v BulkIPAddressRequestStatus) Ptr() *BulkIPAddressRequestStatus {
	return &v
}

type NullableBulkIPAddressRequestStatus struct {
	value *BulkIPAddressRequestStatus
	isSet bool
}

func (v NullableBulkIPAddressRequestStatus) Get() *BulkIPAddressRequestStatus {
	return v.value
}

func (v *NullableBulkIPAddressRequestStatus) Set(val *BulkIPAddressRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkIPAddressRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkIPAddressRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkIPAddressRequestStatus(val *BulkIPAddressRequestStatus) *NullableBulkIPAddressRequestStatus {
	return &NullableBulkIPAddressRequestStatus{value: val, isSet: true}
}

func (v NullableBulkIPAddressRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkIPAddressRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
