/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// ExtrasCustomFieldsListStatusParameter the model 'ExtrasCustomFieldsListStatusParameter'
type ExtrasCustomFieldsListStatusParameter string

// List of extras_custom_fields_list_status_parameter
const (
	EXTRASCUSTOMFIELDSLISTSTATUSPARAMETER_ACTIVE       ExtrasCustomFieldsListStatusParameter = "active"
	EXTRASCUSTOMFIELDSLISTSTATUSPARAMETER_DELETING     ExtrasCustomFieldsListStatusParameter = "deleting"
	EXTRASCUSTOMFIELDSLISTSTATUSPARAMETER_NULL         ExtrasCustomFieldsListStatusParameter = "null"
	EXTRASCUSTOMFIELDSLISTSTATUSPARAMETER_PROVISIONING ExtrasCustomFieldsListStatusParameter = "provisioning"
)

// All allowed values of ExtrasCustomFieldsListStatusParameter enum
var AllowedExtrasCustomFieldsListStatusParameterEnumValues = []ExtrasCustomFieldsListStatusParameter{
	"active",
	"deleting",
	"null",
	"provisioning",
}

func (v *ExtrasCustomFieldsListStatusParameter) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ExtrasCustomFieldsListStatusParameter(value)
	for _, existing := range AllowedExtrasCustomFieldsListStatusParameterEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ExtrasCustomFieldsListStatusParameter", value)
}

// NewExtrasCustomFieldsListStatusParameterFromValue returns a pointer to a valid ExtrasCustomFieldsListStatusParameter
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewExtrasCustomFieldsListStatusParameterFromValue(v string) (*ExtrasCustomFieldsListStatusParameter, error) {
	ev := ExtrasCustomFieldsListStatusParameter(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ExtrasCustomFieldsListStatusParameter: valid values are %v", v, AllowedExtrasCustomFieldsListStatusParameterEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ExtrasCustomFieldsListStatusParameter) IsValid() bool {
	for _, existing := range AllowedExtrasCustomFieldsListStatusParameterEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to extras_custom_fields_list_status_parameter value
func (v ExtrasCustomFieldsListStatusParameter) Ptr() *ExtrasCustomFieldsListStatusParameter {
	return &v
}

type NullableExtrasCustomFieldsListStatusParameter struct {
	value *ExtrasCustomFieldsListStatusParameter
	isSet bool
}

func (v NullableExtrasCustomFieldsListStatusParameter) Get() *ExtrasCustomFieldsListStatusParameter {
	return v.value
}

func (v *NullableExtrasCustomFieldsListStatusParameter) Set(val *ExtrasCustomFieldsListStatusParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableExtrasCustomFieldsListStatusParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableExtrasCustomFieldsListStatusParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExtrasCustomFieldsListStatusParameter(val *ExtrasCustomFieldsListStatusParameter) *NullableExtrasCustomFieldsListStatusParameter {
	return &NullableExtrasCustomFieldsListStatusParameter{value: val, isSet: true}
}

func (v NullableExtrasCustomFieldsListStatusParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExtrasCustomFieldsListStatusParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
