/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkVirtualCircuitRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkVirtualCircuitRequest{}

// PatchedBulkVirtualCircuitRequest Base serializer class for models inheriting from PrimaryModel.
type PatchedBulkVirtualCircuitRequest struct {
	Id int32 `json:"id"`
	// Unique circuit ID
	Cid                  *string                                    `json:"cid,omitempty"`
	ProviderNetwork      *BriefVirtualCircuitRequestProviderNetwork `json:"provider_network,omitempty"`
	ProviderAccount      NullableBulkCircuitRequestProviderAccount  `json:"provider_account,omitempty"`
	Type                 *BulkVirtualCircuitRequestType             `json:"type,omitempty"`
	Status               *BulkCircuitRequestStatus                  `json:"status,omitempty"`
	Tenant               NullableASNRangeRequestTenant              `json:"tenant,omitempty"`
	Description          *string                                    `json:"description,omitempty"`
	Owner                NullableASNRangeRequestOwner               `json:"owner,omitempty"`
	Comments             *string                                    `json:"comments,omitempty"`
	Tags                 []NestedTagRequest                         `json:"tags,omitempty"`
	CustomFields         map[string]interface{}                     `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkVirtualCircuitRequest PatchedBulkVirtualCircuitRequest

// NewPatchedBulkVirtualCircuitRequest instantiates a new PatchedBulkVirtualCircuitRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkVirtualCircuitRequest(id int32) *PatchedBulkVirtualCircuitRequest {
	this := PatchedBulkVirtualCircuitRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkVirtualCircuitRequestWithDefaults instantiates a new PatchedBulkVirtualCircuitRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkVirtualCircuitRequestWithDefaults() *PatchedBulkVirtualCircuitRequest {
	this := PatchedBulkVirtualCircuitRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkVirtualCircuitRequest) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkVirtualCircuitRequest) SetId(v int32) {
	o.Id = v
}

// GetCid returns the Cid field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetCid() string {
	if o == nil || IsNil(o.Cid) {
		var ret string
		return ret
	}
	return *o.Cid
}

// GetCidOk returns a tuple with the Cid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetCidOk() (*string, bool) {
	if o == nil || IsNil(o.Cid) {
		return nil, false
	}
	return o.Cid, true
}

// HasCid returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasCid() bool {
	if o != nil && !IsNil(o.Cid) {
		return true
	}

	return false
}

// SetCid gets a reference to the given string and assigns it to the Cid field.
func (o *PatchedBulkVirtualCircuitRequest) SetCid(v string) {
	o.Cid = &v
}

// GetProviderNetwork returns the ProviderNetwork field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetProviderNetwork() BriefVirtualCircuitRequestProviderNetwork {
	if o == nil || IsNil(o.ProviderNetwork) {
		var ret BriefVirtualCircuitRequestProviderNetwork
		return ret
	}
	return *o.ProviderNetwork
}

// GetProviderNetworkOk returns a tuple with the ProviderNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetProviderNetworkOk() (*BriefVirtualCircuitRequestProviderNetwork, bool) {
	if o == nil || IsNil(o.ProviderNetwork) {
		return nil, false
	}
	return o.ProviderNetwork, true
}

// HasProviderNetwork returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasProviderNetwork() bool {
	if o != nil && !IsNil(o.ProviderNetwork) {
		return true
	}

	return false
}

// SetProviderNetwork gets a reference to the given BriefVirtualCircuitRequestProviderNetwork and assigns it to the ProviderNetwork field.
func (o *PatchedBulkVirtualCircuitRequest) SetProviderNetwork(v BriefVirtualCircuitRequestProviderNetwork) {
	o.ProviderNetwork = &v
}

// GetProviderAccount returns the ProviderAccount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualCircuitRequest) GetProviderAccount() BulkCircuitRequestProviderAccount {
	if o == nil || IsNil(o.ProviderAccount.Get()) {
		var ret BulkCircuitRequestProviderAccount
		return ret
	}
	return *o.ProviderAccount.Get()
}

// GetProviderAccountOk returns a tuple with the ProviderAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualCircuitRequest) GetProviderAccountOk() (*BulkCircuitRequestProviderAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProviderAccount.Get(), o.ProviderAccount.IsSet()
}

// HasProviderAccount returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasProviderAccount() bool {
	if o != nil && o.ProviderAccount.IsSet() {
		return true
	}

	return false
}

// SetProviderAccount gets a reference to the given NullableBulkCircuitRequestProviderAccount and assigns it to the ProviderAccount field.
func (o *PatchedBulkVirtualCircuitRequest) SetProviderAccount(v BulkCircuitRequestProviderAccount) {
	o.ProviderAccount.Set(&v)
}

// SetProviderAccountNil sets the value for ProviderAccount to be an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) SetProviderAccountNil() {
	o.ProviderAccount.Set(nil)
}

// UnsetProviderAccount ensures that no value is present for ProviderAccount, not even an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) UnsetProviderAccount() {
	o.ProviderAccount.Unset()
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetType() BulkVirtualCircuitRequestType {
	if o == nil || IsNil(o.Type) {
		var ret BulkVirtualCircuitRequestType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetTypeOk() (*BulkVirtualCircuitRequestType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given BulkVirtualCircuitRequestType and assigns it to the Type field.
func (o *PatchedBulkVirtualCircuitRequest) SetType(v BulkVirtualCircuitRequestType) {
	o.Type = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetStatus() BulkCircuitRequestStatus {
	if o == nil || IsNil(o.Status) {
		var ret BulkCircuitRequestStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetStatusOk() (*BulkCircuitRequestStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given BulkCircuitRequestStatus and assigns it to the Status field.
func (o *PatchedBulkVirtualCircuitRequest) SetStatus(v BulkCircuitRequestStatus) {
	o.Status = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualCircuitRequest) GetTenant() ASNRangeRequestTenant {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret ASNRangeRequestTenant
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualCircuitRequest) GetTenantOk() (*ASNRangeRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableASNRangeRequestTenant and assigns it to the Tenant field.
func (o *PatchedBulkVirtualCircuitRequest) SetTenant(v ASNRangeRequestTenant) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedBulkVirtualCircuitRequest) SetDescription(v string) {
	o.Description = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedBulkVirtualCircuitRequest) GetOwner() ASNRangeRequestOwner {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret ASNRangeRequestOwner
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedBulkVirtualCircuitRequest) GetOwnerOk() (*ASNRangeRequestOwner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableASNRangeRequestOwner and assigns it to the Owner field.
func (o *PatchedBulkVirtualCircuitRequest) SetOwner(v ASNRangeRequestOwner) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *PatchedBulkVirtualCircuitRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedBulkVirtualCircuitRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedBulkVirtualCircuitRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedBulkVirtualCircuitRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkVirtualCircuitRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedBulkVirtualCircuitRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedBulkVirtualCircuitRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o PatchedBulkVirtualCircuitRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkVirtualCircuitRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Cid) {
		toSerialize["cid"] = o.Cid
	}
	if !IsNil(o.ProviderNetwork) {
		toSerialize["provider_network"] = o.ProviderNetwork
	}
	if o.ProviderAccount.IsSet() {
		toSerialize["provider_account"] = o.ProviderAccount.Get()
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkVirtualCircuitRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	// defaultValueFuncMap captures the default values for required properties.
	// These values are used when required properties are missing from the payload.
	defaultValueFuncMap := map[string]func() interface{}{}
	var defaultValueApplied bool
	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			if _, ok := defaultValueFuncMap[requiredProperty]; ok {
				allProperties[requiredProperty] = defaultValueFuncMap[requiredProperty]()
				defaultValueApplied = true
			}
		}
		if value, exists := allProperties[requiredProperty]; !exists || value == "" {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	if defaultValueApplied {
		data, err = json.Marshal(allProperties)
		if err != nil {
			return err
		}
	}
	varPatchedBulkVirtualCircuitRequest := _PatchedBulkVirtualCircuitRequest{}

	err = json.Unmarshal(data, &varPatchedBulkVirtualCircuitRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkVirtualCircuitRequest(varPatchedBulkVirtualCircuitRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "cid")
		delete(additionalProperties, "provider_network")
		delete(additionalProperties, "provider_account")
		delete(additionalProperties, "type")
		delete(additionalProperties, "status")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "description")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkVirtualCircuitRequest struct {
	value *PatchedBulkVirtualCircuitRequest
	isSet bool
}

func (v NullablePatchedBulkVirtualCircuitRequest) Get() *PatchedBulkVirtualCircuitRequest {
	return v.value
}

func (v *NullablePatchedBulkVirtualCircuitRequest) Set(val *PatchedBulkVirtualCircuitRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkVirtualCircuitRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkVirtualCircuitRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkVirtualCircuitRequest(val *PatchedBulkVirtualCircuitRequest) *NullablePatchedBulkVirtualCircuitRequest {
	return &NullablePatchedBulkVirtualCircuitRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkVirtualCircuitRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkVirtualCircuitRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
