/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.7.2-Docker-5.1.1 (4.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// BulkLocationRequestStatus * `planned` - Planned * `staging` - Staging * `active` - Active * `decommissioning` - Decommissioning * `retired` - Retired
type BulkLocationRequestStatus string

// List of BulkLocationRequest_status
const (
	BULKLOCATIONREQUESTSTATUS_PLANNED         BulkLocationRequestStatus = "planned"
	BULKLOCATIONREQUESTSTATUS_STAGING         BulkLocationRequestStatus = "staging"
	BULKLOCATIONREQUESTSTATUS_ACTIVE          BulkLocationRequestStatus = "active"
	BULKLOCATIONREQUESTSTATUS_DECOMMISSIONING BulkLocationRequestStatus = "decommissioning"
	BULKLOCATIONREQUESTSTATUS_RETIRED         BulkLocationRequestStatus = "retired"
)

// All allowed values of BulkLocationRequestStatus enum
var AllowedBulkLocationRequestStatusEnumValues = []BulkLocationRequestStatus{
	"planned",
	"staging",
	"active",
	"decommissioning",
	"retired",
}

func (v *BulkLocationRequestStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BulkLocationRequestStatus(value)
	for _, existing := range AllowedBulkLocationRequestStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BulkLocationRequestStatus", value)
}

// NewBulkLocationRequestStatusFromValue returns a pointer to a valid BulkLocationRequestStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBulkLocationRequestStatusFromValue(v string) (*BulkLocationRequestStatus, error) {
	ev := BulkLocationRequestStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BulkLocationRequestStatus: valid values are %v", v, AllowedBulkLocationRequestStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BulkLocationRequestStatus) IsValid() bool {
	for _, existing := range AllowedBulkLocationRequestStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BulkLocationRequest_status value
func (v BulkLocationRequestStatus) Ptr() *BulkLocationRequestStatus {
	return &v
}

type NullableBulkLocationRequestStatus struct {
	value *BulkLocationRequestStatus
	isSet bool
}

func (v NullableBulkLocationRequestStatus) Get() *BulkLocationRequestStatus {
	return v.value
}

func (v *NullableBulkLocationRequestStatus) Set(val *BulkLocationRequestStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkLocationRequestStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkLocationRequestStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkLocationRequestStatus(val *BulkLocationRequestStatus) *NullableBulkLocationRequestStatus {
	return &NullableBulkLocationRequestStatus{value: val, isSet: true}
}

func (v NullableBulkLocationRequestStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkLocationRequestStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
