---
generatorName: go

gitHost: github.com
gitUserId: smutel
gitRepoId: go-netbox/v4

packageName: netbox

globalProperty:
  apiDocs: false
  modelDocs: false
  apiTests: false
  modelTests: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: "false"
  generateInterfaces: "true"
  packageVersion: "4"
  enumClassPrefix: "true"
  useDefaultValuesForRequiredVars: "true"
