---
name: PR

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Check conventional commits in PR
        uses: Namchee/conventional-pr@a6f50a1a97809e18975759853b67e45246005369  # v0.15.6
        with:
          access_token: ${{ secrets.github_token }}
          close: false
          strict: false
          report: false

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup env
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
          mkdir -p "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel"
          ln -sf "$GITHUB_WORKSPACE/" "$(dirname $GITHUB_WORKSPACE)/src/github.com/smutel/go-netbox"
        shell: bash

      - name: Generate netbox client
        run: |
          sudo apt-get -q install python3-demjson
          cd "$GITHUB_WORKSPACE/utils"
          ./netbox_generate_client
        shell: bash

      - name: Show git diff
        run: |
          git add -N .
          git diff
        shell: bash
